# -*- coding: utf-8 -*-
"""Conteúdo de documentação e venda dos produtos 06-10."""

SPECS = []

# ============================================================================================ 06
SPECS.append(dict(
    mod="p06_dre", op=6, categoria="Financeiro", preco=(57, 47, 97),
    comercial="DRE e Ponto de Equilíbrio", slogan="Descubra o lucro real e quanto precisa vender para pagar as contas.",
    dor="A empresa fatura, mas o dono não sabe se tem lucro nem quanto precisa vender por mês para não ter prejuízo.",
    resumo="Monta o DRE mensal a partir de lançamentos simples e calcula margem de contribuição, ponto de equilíbrio, margem de segurança e faturamento necessário para a meta de lucro.",
    para_que=["Transformar os lançamentos em um DRE (Demonstração do Resultado) mês a mês, sem fórmulas para montar.", "Calcular o ponto de equilíbrio: o faturamento mínimo para não ter prejuízo.",
              "Mostrar quanto precisa faturar para atingir o lucro mensal que você deseja e se você está acima ou abaixo do equilíbrio."],
    publico=["Pequenas e médias empresas que só veem o lucro no balanço do contador", "Sócios e gestores iniciantes em finanças", "Lojas, indústrias leves e prestadores com custos fixos relevantes", "Empresas que querem negociar crédito com números organizados"],
    antes=["Faturamento de cada mês (por competência: quando vendeu).", "Custos variáveis: mercadorias, insumos, comissões, taxas e impostos sobre vendas.", "Despesas fixas: folha e pró-labore, aluguel, energia, contador, marketing.",
           "Despesas e receitas financeiras (juros, tarifas, rendimentos).", "O lucro líquido mensal que você deseja."],
    abas=[("Início", "Instruções."), ("Config", "Empresa, ano, lucro desejado e a lista das 10 contas do DRE com o que lançar em cada uma."), ("Lançamentos", "Todos os lançamentos (1.500 linhas)."),
          ("DRE", "Demonstração mensal com total do ano e % da receita bruta."), ("Ponto de Equilíbrio", "Indicadores, PE por mês, situação e gráficos.")],
    passo1=("Configure o ano e a meta", ["Abra **Config**.", "Em **C4** o nome da empresa, em **C5** o ano do DRE e em **C6** o lucro líquido mensal desejado.", "Leia a tabela de contas (**B10:D19**) para saber o que lançar em cada uma. Não renomeie as contas."], "img/inicio.png"),
    passo2=("Lance as receitas, custos e despesas", ["Abra **Lançamentos** e clique em **A5**.", "Preencha **Data** (competência), **Conta do DRE** (lista), **Descrição** e **Valor** (sempre positivo).",
                                                    "Receitas vão em 'Receita bruta' (e 'Receitas financeiras'). Todo o resto é custo ou despesa; a conta define se é fixo ou variável.", "Dica: lance por semana ou por mês, o que for mais prático (uma linha por conta por mês já basta)."], "img/lancamentos.png"),
    passo3=("Leia o DRE e o ponto de equilíbrio", ["Abra **DRE**: cada coluna é um mês; a última é o total do ano e a coluna **% da receita bruta** mostra o peso de cada linha.",
                                                  "**Margem de contribuição** = receita líquida - custos variáveis - comissões. É o que sobra para pagar as despesas fixas.", "Abra **Ponto de Equilíbrio**: custos fixos ÷ margem de contribuição % = faturamento mínimo.",
                                                  "A coluna **Situação** mostra 'Acima do PE' ou 'ABAIXO do PE' em cada mês."], "img/dre.png"),
    indicadores=[("Receita líquida", "Receita bruta - deduções e impostos sobre vendas."), ("Margem de contribuição (%)", "Quanto de cada R$ 100 vendidos sobra após custos variáveis e impostos."),
                 ("Resultado operacional", "O que a operação gera antes das despesas financeiras e do IR."), ("Lucro líquido / Margem líquida", "O resultado final e quanto ele representa da receita bruta."),
                 ("Ponto de equilíbrio (R$)", "Custos fixos ÷ MC%. Abaixo disso há prejuízo."), ("Margem de segurança", "Quanto a receita pode cair antes de chegar ao equilíbrio.")],
    exemplo=["Empresa fictícia com lançamentos de janeiro a setembro de 2026 (receita de cerca de R$ 66 mil a R$ 123 mil por mês) e meta de lucro de R$ 8.000,00 por mês.",
             "Receita bruta no ano: **{{Ponto de Equilíbrio!A5|money}}**; lucro líquido: **{{Ponto de Equilíbrio!C5|money}}** (margem líquida **{{Ponto de Equilíbrio!E5|pct}}**); margem de contribuição: **{{Ponto de Equilíbrio!G5|pct}}**.",
             "Ponto de equilíbrio médio: **{{Ponto de Equilíbrio!I5|money}}** por mês; margem de segurança: **{{Ponto de Equilíbrio!A8|pct}}**; para ter R$ 8 mil de lucro por mês é preciso faturar **{{Ponto de Equilíbrio!E8|money}}**.",
             "Meses acima do PE: **{{Ponto de Equilíbrio!G8|int}}**; abaixo: **{{Ponto de Equilíbrio!I8|int}}**. Os meses de início de ano ficam abaixo do equilíbrio: sazonalidade a tratar com reserva ou promoções."],
    diario=["Nada obrigatório: o DRE é mensal."], semanal=["Lance as notas de compra e as despesas da semana."],
    mensal=["Até o dia 10: lance a receita e todas as despesas do mês anterior.", "Compare lucro líquido e margem com a meta.", "Verifique se o mês ficou acima do ponto de equilíbrio e se o custo fixo cresceu."],
    erros=[("Lançar pelo dia do pagamento em vez da competência", "O DRE mostra quando a venda/gasto ocorreu. Para caixa use o Fluxo de Caixa."),
           ("Misturar compra de ativo com despesa", "Compra de máquina não é despesa do mês; lance só a depreciação (se controlar) ou deixe fora e use o Fluxo de Caixa."),
           ("Esquecer o pró-labore", "Sem ele o lucro parece maior. Lance em 'Despesas com pessoal'."),
           ("Lançar impostos do Simples como IRPJ/CSLL", "No Simples Nacional, o DAS entra em 'Deduções e impostos sobre vendas'. IRPJ/CSLL é só para Lucro Presumido/Real."),
           ("Meses sem receita", "Meses sem receita não calculam o PE (mostram vazio). Lance a receita para ver o indicador.")],
    faq=[("Substitui o DRE do contador?", "Não. É um DRE gerencial para decisão rápida; o contador entrega o oficial."),
         ("O que é competência?", "O mês em que a venda ou o custo aconteceu, independentemente de quando foi pago."),
         ("Posso ter mais de um ano?", "Use uma cópia da planilha para cada ano (o campo Ano da Config filtra o relatório)."),
         ("Posso detalhar mais as despesas?", "Use a coluna Descrição. As 10 contas são a estrutura fixa do DRE."),
         ("Como interpreto margem de segurança negativa?", "Significa receita abaixo do ponto de equilíbrio: a empresa está no prejuízo operacional.")],
    vantagens=["DRE pronto a partir de lançamentos simples.", "Ponto de equilíbrio mês a mês e para a meta de lucro.", "Análise vertical automática (% da receita).", "Gráficos de lucro e de receita x equilíbrio.", "Estrutura pensada para pequenas empresas."],
    objecoes=[("Meu contador já faz o DRE.", "Ele entrega meses depois. Esta planilha mostra o lucro enquanto ainda dá tempo de agir."),
              ("Contabilidade é complicado.", "A planilha usa só 10 contas e o Tutorial traz um exemplo completo."),
              ("Meu negócio não tem custo fixo.", "Mesmo MEI tem pró-labore, internet e sistemas; veja o ponto de equilíbrio dele.")],
    preco_just="Planilha de gestão com alto valor de decisão, mas com concorrência de modelos de DRE gratuitos de blogs contábeis; o diferencial é o ponto de equilíbrio integrado e o tutorial. Premium: comparativo com orçamento e DRE por centro de custo.",
    kits=["Kit Pequeno Empresário", "Kit Construtora", "Kit Clínica", "Kit Completo"],
    pitch30="Sua empresa dá lucro de verdade? Com o DRE e Ponto de Equilíbrio você lança receitas e despesas e a planilha monta o DRE mensal, calcula a margem de contribuição e mostra quanto precisa faturar para não ter prejuízo e para chegar ao lucro que você quer.",
    cap="1.500 lançamentos por ano.",
))

# ============================================================================================ 07
SPECS.append(dict(
    mod="p07_ficha", op=7, categoria="Restaurantes", preco=(77, 67, 127),
    comercial="Ficha Técnica e CMV para Restaurantes", slogan="Saiba quanto custa cada prato e onde seu dinheiro está sumindo.",
    dor="O cardápio é precificado 'no feeling' e o CMV fica alto por desperdício, porção irregular ou fornecedor caro, sem o dono saber onde.",
    resumo="Cadastro de insumos com fator de correção, fichas técnicas, CMV e preço sugerido por prato, engenharia de cardápio, CMV real x teórico mensal e registro de desperdício.",
    para_que=["Calcular o custo exato de cada prato (por porção) e o CMV de cada item do cardápio.", "Descobrir quais pratos estão acima da meta, quais são 'estrela' e quais deveriam sair do cardápio.",
              "Comparar o CMV real do mês (estoque + compras) com o CMV teórico das fichas e registrar o desperdício."],
    publico=["Restaurantes, bares e lanchonetes", "Pizzarias, hamburguerias e padarias", "Confeitarias e marmitarias", "Dark kitchens e delivery"],
    antes=["Lista de insumos com preço e quantidade da embalagem (nota fiscal de compra).", "Receitas dos pratos com a quantidade líquida de cada ingrediente.", "Preço de venda e quantidade vendida de cada prato no mês.",
           "Estoque inicial, compras e estoque final do mês em R$ (contagem física).", "Faturamento do mês."],
    abas=[("Início", "Instruções."), ("Config", "Meta de CMV, impostos/taxas, mês de referência, listas."), ("Insumos", "Custo por unidade bruto e útil (com fator de correção)."),
          ("Fichas", "Receitas: insumo e quantidade por prato."), ("Pratos", "Custo/porção, CMV, preço sugerido, classe do cardápio."), ("CMV Mensal", "CMV real x teórico e perdas."), ("Desperdício", "Registro de perdas por motivo."), ("Dashboard", "Indicadores, 5 piores pratos, desperdício.")],
    passo1=("Configure e cadastre os insumos", ["Abra **Config**: **C5** meta de CMV (ex.: 32%), **C6** impostos+taxas sobre a venda, **C7** mês de referência (1º dia do mês, ex.: 01/09/2026) e **C8** o ano.", "Abra **Insumos** e preencha: **Insumo**, **Unidade**, **Preço da embalagem**, **Qtd na embalagem** e **Fator de correção** (1 se não há perda).",
                                              "O custo por unidade útil é calculado: custo por unidade bruto x fator de correção."], "img/inicio.png"),
    passo2=("Cadastre os pratos e monte as fichas", ["Abra **Pratos**: **Prato**, **Categoria**, **Rendimento** (porções que a receita rende), **Preço de venda** e **Qtd vendida no mês**.", "Abra **Fichas**: em cada linha escolha o **Prato**, o **Insumo** e a **Quantidade líquida** usada em 1 receita, na unidade do insumo (0,150 para 150 g quando a unidade é kg).",
                                                    "Veja em **Pratos** o **CUSTO POR PORÇÃO**, o **CMV %** e o **Status vs meta**. A coluna *Preço sugerido* mostra o preço necessário para atingir a meta."], "img/pratos.png"),
    passo3=("Feche o mês e registre o desperdício", ["Abra **CMV Mensal** e, na linha do mês, preencha **Estoque inicial**, **Compras**, **Estoque final** e **Receita de vendas** (R$).", "A planilha calcula o **CMV real** e, no mês de referência, o **CMV teórico** (quantidades vendidas x custo das fichas).",
                                                     "A **Diferença** mostra quanto foi perdido além do esperado; **Perdas registradas** vem da aba **Desperdício** (data, insumo, quantidade, motivo); o restante é *Perda sem explicação*.", "O **Dashboard** mostra os 5 piores pratos, a engenharia de cardápio e as perdas por motivo."], "img/cmv-mensal.png"),
    indicadores=[("Custo por porção", "Soma do custo útil dos insumos ÷ rendimento."), ("CMV % do prato", "Custo por porção ÷ preço de venda."), ("Classe do cardápio", "Estrela (vende e lucra), Burro de carga (vende, margem baixa), Quebra-cabeça (lucra, vende pouco), Cão (nem vende nem lucra)."),
                 ("CMV real x teórico", "Real = (estoque inicial + compras - estoque final) ÷ receita. Teórico = o que as fichas dizem. A diferença são perdas."), ("Perda sem explicação", "Diferença que não está registrada como desperdício: investigar (furto, porção maior, erro de contagem).")],
    exemplo=["Restaurante fictício com 26 insumos, 14 pratos e fichas completas; mês de referência: setembro de 2026; meta de CMV de 32%.",
             "CMV real: **{{Dashboard!A5|pct}}** x CMV teórico: **{{Dashboard!C5|pct}}** (meta **{{Dashboard!E5|pct}}**). Diferença de **{{Dashboard!G5|n1}}** pontos percentuais acima do esperado.",
             "Perdas registradas no mês: **{{Dashboard!I5|money}}**; perda sem explicação: **{{Dashboard!I8|money}}**. Pratos acima da meta: **{{Dashboard!A8|int}}**; pratos Estrela: **{{Dashboard!C8|int}}**; Cães: **{{Dashboard!E8|int}}**.",
             "Margem de contribuição do mês no cardápio: **{{Dashboard!G8|money}}**. O prato com pior CMV é **{{Dashboard!B12|txt}}**."],
    diario=["Registre qualquer desperdício na aba Desperdício (data, insumo, quantidade, motivo).", "Atualize o preço do insumo quando chegar nota fiscal com valor novo."],
    semanal=["Revise o preço de compra dos insumos mais usados.", "Veja os pratos com status ACIMA DA META."],
    mensal=["No 1º dia do mês, faça a contagem física do estoque.", "Preencha CMV Mensal e a quantidade vendida de cada prato.", "Decida: manter Estrelas, reprecificar Burros de carga, divulgar Quebra-cabeças e reformular Cães."],
    erros=[("Quantidade na ficha em unidade diferente do insumo", "Se o insumo está em kg, a ficha usa kg (0,150 e não 150). A coluna Unidade da ficha mostra a unidade esperada."),
           ("Esquecer o fator de correção", "Sem FC o custo do prato fica menor que o real (ex.: carnes, legumes). Use bruto ÷ líquido."),
           ("Rendimento errado", "Se a receita rende 4 porções, informe 4 no Rendimento; senão o custo por porção fica 4x maior."),
           ("Esquecer de lançar a quantidade vendida", "Sem ela não há classe do cardápio nem CMV teórico."),
           ("Estoque final estimado", "Faça contagem física; estimativa distorce o CMV real.")],
    faq=[("O que é fator de correção?", "É a relação bruto ÷ líquido. Se 1 kg de frango rende 870 g limpos, FC = 1,15."),
         ("Qual CMV é ideal?", "Depende do tipo de restaurante; referências de mercado citam entre 25% e 40%. Defina sua meta na Config."),
         ("Posso usar para delivery?", "Sim: cadastre o preço do delivery como outro prato ou ajuste o preço de venda; a versão premium terá margem por plataforma."),
         ("E bebidas e produtos prontos?", "Cadastre como insumo e prato com 1 ingrediente (veja Refrigerante lata no exemplo)."),
         ("Quantos pratos e insumos?", "100 pratos, 300 insumos, 800 linhas de ficha e 500 registros de desperdício.")],
    vantagens=["Engenharia de cardápio automática.", "CMV real x teórico: mostra perdas que ninguém vê.", "Preço sugerido por meta de CMV.", "Registro de desperdício por motivo.", "Atualiza todas as fichas quando o preço do insumo muda."],
    objecoes=[("Já faço o CMV no fim do mês.", "O CMV do mês só diz que algo deu errado. A ficha mostra em qual prato e o registro de desperdício mostra o motivo."),
              ("Tenho cardápio grande.", "Comece pelos 10 pratos mais vendidos: costumam representar mais de 70% das vendas."),
              ("Cozinha não tem tempo de pesar.", "A ficha é feita uma vez; depois só atualizar preços. Pese uma vez cada receita.")],
    preco_just="Nicho com dor alta e disposição a pagar (CMV impacta diretamente o lucro) e pouca planilha gratuita com engenharia de cardápio e CMV real x teórico. Complexidade alta. Premium: delivery (margem por plataforma) e histórico de preço de insumos.",
    kits=["Kit Restaurante", "Kit Completo"],
    pitch30="Seu prato mais vendido dá lucro? Com a Ficha Técnica e CMV você calcula o custo exato de cada porção, descobre quais pratos estão acima da meta, classifica o cardápio em estrela, burro de carga, quebra-cabeça e cão e compara o CMV real com o teórico para achar o desperdício.",
    cap="300 insumos, 100 pratos, 800 linhas de ficha e 500 registros de desperdício.",
))

# ============================================================================================ 08
SPECS.append(dict(
    mod="p08_oficina", op=8, categoria="Oficinas", preco=(77, 67, 127),
    comercial="Ordem de Serviço para Oficinas", slogan="Cada peça na OS, cada real no caixa.",
    dor="Orçamento no WhatsApp, peça controlada 'de cabeça', estoque que some e caixa que não fecha com o movimento real.",
    resumo="Ordem de serviço com clientes, veículos, peças, estoque, lucro por OS, comissão de mecânico, contas a receber, OS atrasadas e histórico por placa.",
    para_que=["Abrir e acompanhar ordens de serviço com mão de obra, peças e terceiros.", "Dar baixa automática no estoque de peças e avisar o que está em ruptura.", "Mostrar lucro por OS, quanto falta receber, OS atrasadas e o faturamento do mês."],
    publico=["Oficinas mecânicas e auto centers", "Auto elétricas e funilarias", "Retíficas e oficinas de motos", "Qualquer oficina que ainda usa talão e caderno"],
    antes=["Valor da hora de mão de obra e percentual de comissão dos mecânicos.", "Lista de peças com custo e (opcional) preço de venda.", "Estoque atual das peças principais.", "Lista de clientes e veículos (nome, placa, modelo)."],
    abas=[("Início", "Instruções."), ("Config", "Valor da hora, markup, comissão, prazo, mecânicos, pagamentos."), ("Clientes", "Cadastro."), ("Veículos", "Placa, modelo, ano e cliente."), ("Peças", "Cadastro com estoque atual e situação."),
          ("Entradas", "Compras de peças."), ("OS", "Ordens de serviço com totais e lucro."), ("Itens da OS", "Peças usadas em cada OS."), ("Histórico", "Todas as OS de uma placa."), ("Dashboard", "Faturamento, lucro, OS atrasadas, a receber e estoque.")],
    passo1=("Configure a oficina", ["Abra **Config**: **C6** valor da hora de mão de obra, **C7** markup padrão sobre peças (ex.: 40%), **C8** comissão dos mecânicos sobre a mão de obra, **C9** prazo máximo de uma OS aberta (dias).", "Cadastre os mecânicos em **E5:E14** e as formas de pagamento em **G5:G14**.",
                                    "Cadastre **Clientes**, **Veículos** (placa única e cliente) e **Peças** (código, descrição, custo, estoque inicial e mínimo; preço fixo é opcional)."], "img/inicio.png"),
    passo2=("Abra a OS e lance as peças", ["Abra **OS**. Em uma linha nova: **Nº OS** (único), **Data de entrada**, **Placa** (lista), **Km**, **Serviço**, **Mecânico**, **Status** e **Horas de mão de obra**.", "Abra **Itens da OS** e, para cada peça usada, informe o **Nº OS**, o **Código da peça** e a **Quantidade**. O preço vem da tabela de peças (ou digite outro).",
                                         "Mude o status ao longo do serviço: Orçamento → Aprovado → Em execução → Aguardando peça → Finalizado → Entregue.", "O estoque só baixa quando o status sai de 'Orçamento' (e não é 'Cancelada')."], "img/os.png"),
    passo3=("Entregue, receba e acompanhe", ["Ao entregar, mude para **Entregue** e preencha **Data de entrega**, **Forma de pagamento** e **Valor recebido**.", "A OS calcula **TOTAL**, **Custo das peças**, **Comissão**, **LUCRO BRUTO**, **Margem** e **Saldo a receber**; a coluna **ALERTA** mostra ATRASADA ou Cobrar.",
                                      "Abra **Histórico**, escolha a placa em **C4** e veja todas as OS dela. O **Dashboard** mostra faturamento do mês, ticket médio, lucro, OS atrasadas e peças em ruptura."], "img/dashboard.png"),
    indicadores=[("Total da OS", "Mão de obra + peças + terceiros - desconto."), ("Lucro bruto", "Total - custo das peças - comissão do mecânico - terceiros."), ("Margem", "Lucro bruto ÷ total da OS."),
                 ("Saldo a receber", "OS finalizada/entregue com valor recebido menor que o total."), ("OS atrasadas", "Aprovadas/em execução/aguardando peça há mais dias que o prazo."), ("Estoque de peças", "Situação RUPTURA / REPOR / OK pelo estoque mínimo.")],
    exemplo=["Oficina fictícia com 18 clientes, 24 peças e 96 ordens de serviço entre junho e outubro de 2026.",
             "Faturamento do mês: **{{Dashboard!A5|money}}** com **{{Dashboard!C5|int}}** OS entregues (ticket médio **{{Dashboard!E5|money}}**); lucro bruto **{{Dashboard!G5|money}}** (margem **{{Dashboard!I5|pct}}**).",
             "OS em andamento: **{{Dashboard!A8|int}}**, sendo **{{Dashboard!C8|int}}** aguardando peça e **{{Dashboard!G8|int}}** atrasadas; a receber: **{{Dashboard!E8|money}}**.",
             "Peças em ruptura: **{{Dashboard!A11|int}}**; estoque de peças ao custo: **{{Dashboard!E11|money}}**."],
    diario=["Abra as OS do dia e atualize status.", "Lance as peças usadas e as entregas com valor recebido."],
    semanal=["Revise OS ATRASADAS e 'Aguardando peça'.", "Cobre os clientes com status Cobrar."],
    mensal=["Veja faturamento, lucro e comissão por mecânico.", "Reponha as peças em RUPTURA/REPOR.", "Atualize o valor da hora e o markup se necessário."],
    erros=[("Usar Nº de OS repetido", "A validação bloqueia repetição. Cada OS tem um número único."),
           ("Lançar peças sem Nº de OS correto", "A coluna Conferência de Itens da OS mostra 'OS inexistente'. Corrija o número."),
           ("Esquecer de mudar o status para Entregue", "O faturamento do mês só considera OS Entregue com data de entrega."),
           ("Placa não cadastrada", "Cadastre o veículo antes (aba Veículos) para o cliente e o modelo aparecerem."),
           ("Peça sem custo cadastrado", "Sem custo o lucro fica inflado. Preencha o custo das peças.")],
    faq=[("Emite nota fiscal?", "Não. A planilha controla a operação; a emissão é feita no seu sistema fiscal."),
         ("Posso mudar o texto dos status?", "Os status são fixos para que os cálculos funcionem."),
         ("Como funciona o preço das peças?", "Se o preço fixo estiver vazio, usa custo + markup da Config."),
         ("A comissão incide sobre peças?", "Não: só sobre a mão de obra (percentual da Config)."),
         ("Quantas OS cabem?", "1.000 OS, 3.000 itens, 500 peças, 300 clientes e veículos.")],
    vantagens=["Lucro por OS: veja quais serviços dão dinheiro.", "Baixa de estoque automática pelas OS.", "Histórico por placa para fidelização.", "Alertas de OS atrasada e cobrança.", "Sem mensalidade."],
    objecoes=[("Já uso talão de OS.", "O talão não soma, não baixa estoque nem mostra lucro. A planilha faz isso sozinha."),
              ("Meus mecânicos não usam computador.", "Só quem fecha a OS lança no computador, uma vez por dia."),
              ("Tem sistema para oficina.", "Sistemas custam mensalidade. A planilha custa uma vez e já resolve o essencial.")],
    preco_just="Concorrentes são sistemas com mensalidade; a planilha entrega o essencial por pagamento único. Complexidade alta (10 abas) e evidência de dor vem de fornecedores (média). Premium: checklist de entrada, orçamento imprimível e revisão programada por km.",
    kits=["Kit Oficina", "Kit Completo"],
    pitch30="Quanto sua oficina realmente lucra por ordem de serviço? A planilha de OS controla clientes, veículos, peças e estoque, calcula o lucro de cada OS, avisa OS atrasadas e cobranças, e mostra o histórico por placa e o faturamento do mês.",
    cap="1.000 OS, 3.000 itens, 500 peças, 300 clientes/veículos.",
))

# ============================================================================================ 09
SPECS.append(dict(
    mod="p09_obras", op=9, categoria="Construção", preco=(87, 77, 147),
    comercial="Controle de Obras (Orçado x Realizado)", slogan="Descubra o estouro de custo e prazo enquanto ainda dá tempo de agir.",
    dor="A obra estoura custo e prazo, e o dono só descobre a margem no fim.",
    resumo="Controle de obra com orçamento por etapa, custos reais, cronograma com Gantt, % físico, projeção do custo final, margem prevista e medições recebidas.",
    para_que=["Comparar o orçado com o realizado por etapa e por categoria de custo.", "Projetar o custo final da obra (custo real ÷ % físico) e a margem prevista em relação ao contrato.",
              "Acompanhar o cronograma em Gantt, as etapas atrasadas e o caixa da obra (recebido x pago)."],
    publico=["Pequenas construtoras e empreiteiras", "Engenheiros e arquitetos que gerenciam obra", "Empresas de reforma e manutenção predial", "Quem constrói por administração e precisa prestar contas"],
    antes=["Valor do contrato (ou preço de venda).", "Orçamento detalhado por etapa (itens, quantidades e custos unitários).", "Cronograma: início e fim previstos de cada etapa.", "Notas e pagamentos já feitos.", "Medições emitidas e recebidas."],
    abas=[("Início", "Instruções."), ("Config", "Obra, contrato, datas, margem mínima, categorias e fornecedores."), ("Cronograma", "Etapas, datas, % físico, situação e Gantt semanal."), ("Orçamento", "Itens orçados por etapa e categoria."),
          ("Custos", "Custos reais (1.500 linhas)."), ("Medições", "Faturamentos e recebimentos."), ("Resumo", "Orçado x realizado, EAC, margem e gráficos.")],
    passo1=("Cadastre a obra e as etapas", ["Abra **Config** e preencha: **C4** obra, **C5** cliente, **C6** valor do contrato, **C7** início e **C8** fim previstos e **C9** margem mínima aceitável.", "Abra **Cronograma** e liste até 20 etapas em **A5:A24** com **Início previsto** e **Fim previsto** (colunas B e C).",
                                            "O Gantt semanal aparece automaticamente à direita (verde claro = previsto; verde escuro = executado)."], "img/cronograma.png"),
    passo2=("Monte o orçamento e lance os custos", ["Abra **Orçamento** e, para cada etapa (lista), informe **Item**, **Categoria**, **Un.**, **Quantidade** e **Custo unitário**. O total orçado é calculado.", "Abra **Custos** e lance cada nota/pagamento: **Data**, **Etapa**, **Categoria**, **Fornecedor**, **Descrição**, **Valor** e **Status** (Pago ou A pagar).",
                                                   "Abra **Medições** e registre cada faturamento: número, data, valor, vencimento; ao receber, data e valor recebido."], "img/inicio.png"),
    passo3=("Atualize o % físico e leia o Resumo", ["Toda semana abra **Cronograma** e atualize o **% físico executado** (coluna D) de cada etapa.", "Abra **Resumo**: veja orçado, realizado, % custo consumido x % físico, **custo final projetado (EAC)** e **margem prevista**.",
                                                  "O quadro por etapa mostra o desvio projetado em R$ e a situação do cronograma (Concluída, Em dia, ATRASADA, A iniciar). O alerta indica se a margem está abaixo da meta."], "img/resumo.png"),
    indicadores=[("% custo consumido", "Realizado ÷ orçado. Comparar com o % físico: custo consumindo mais que o avanço = alerta."), ("Custo projetado (EAC)", "Custo real ÷ % físico de cada etapa (ou o orçado se o avanço é menor que 5%)."),
                 ("Margem prevista", "Contrato - custo projetado. Compare com a margem orçada e a meta."), ("Desvio projetado", "Custo projetado - orçado da etapa. Positivo (vermelho) = estouro."),
                 ("Situação da etapa", "ATRASADA se o % físico está mais de 10 pontos abaixo do % de tempo decorrido."), ("Saldo de caixa da obra", "Recebido das medições - custos pagos.")],
    exemplo=["Reforma comercial fictícia de R$ 480.000,00, de 04/05/2026 a 18/12/2026, com 10 etapas; hoje = 08/10/2026.",
             "Orçado: **{{Resumo!B5|money}}**; realizado: **{{Resumo!D5|money}}** (**{{Resumo!F5|pct}}** do orçado) com **{{Resumo!H5|pct}}** de avanço físico.",
             "Custo final projetado: **{{Resumo!A8|money}}** → margem prevista **{{Resumo!B8|money}}** (**{{Resumo!D8|pct}}**) contra margem orçada de **{{Resumo!F8|pct}}**: alerta **{{Resumo!H8|txt}}**.",
             "Recebido: **{{Resumo!A11|money}}**; pago: **{{Resumo!B11|money}}**; saldo de caixa: **{{Resumo!D11|money}}**; a receber: **{{Resumo!F11|money}}**; etapas atrasadas: **{{Resumo!H11|int}}**."],
    diario=["Lance os custos e notas do dia (ou da semana)."], semanal=["Atualize o % físico de cada etapa.", "Revise etapas ATRASADAS e desvios projetados."],
    mensal=["Emita a medição e lance o recebimento.", "Compare margem prevista x orçada e decida correções (renegociar, trocar fornecedor, reforçar equipe).", "Reprograme etapas atrasadas no cronograma."],
    erros=[("Nome de etapa diferente nas abas", "Use a lista suspensa. A aba Custos mostra 'Etapa inválida' quando não bate."),
           ("Não atualizar o % físico", "A projeção do custo final depende dele; sem atualizar, o EAC fica irreal."),
           ("Lançar adiantamentos como custo total", "Lance o valor efetivamente consumido da etapa para não distorcer a projeção."),
           ("Esquecer custos indiretos", "Crie uma etapa 'Administração da obra' para equipe, canteiro e taxas."),
           ("Data de início da obra em branco", "O Gantt precisa do início da Config para montar as semanas.")],
    faq=[("Dá para usar para vários contratos?", "Use uma cópia da planilha por obra."), ("Serve para reforma pequena?", "Sim; use poucas etapas (ex.: demolição, elétrica, acabamento)."),
         ("O Gantt precisa de macros?", "Não: é feito com formatação condicional, funciona em Excel e LibreOffice."), ("A projeção é exata?", "É uma estimativa baseada no avanço físico; revise com o engenheiro responsável."),
         ("Quantas etapas e itens?", "20 etapas, 300 itens de orçamento, 1.500 custos e 60 medições.")],
    vantagens=["Projeção do custo final e da margem durante a obra.", "Gantt automático por formatação condicional.", "Orçado x realizado por etapa e categoria.", "Medições e saldo de caixa da obra.", "Alertas de etapa atrasada e margem abaixo da meta."],
    objecoes=[("Uso um software de orçamento.", "Esses softwares não projetam a margem final com base no avanço físico; use a planilha como painel de controle."),
              ("Minha obra é pequena.", "Obras pequenas têm margem apertada: um estouro de 5% pode eliminar o lucro."),
              ("Meu mestre de obras não sabe lançar.", "Só o escritório lança notas; o mestre informa o avanço físico semanalmente.")],
    preco_just="Ticket mais alto da primeira leva: dinheiro envolvido em obra é grande e a planilha evita estouros de milhares de reais. Complexidade alta (7 abas, Gantt, EAC). Concorrência: softwares caros e planilhas de engenharia. Premium: curva S, medições por item e comparativo de fornecedores.",
    kits=["Kit Construtora", "Kit Completo"],
    pitch30="Sua obra vai terminar com lucro? O Controle de Obras compara orçado e realizado por etapa, mostra o cronograma em Gantt, projeta o custo final pelo avanço físico e calcula a margem prevista antes de a obra acabar. Inclui medições e caixa da obra.",
    cap="20 etapas, 300 itens de orçamento, 1.500 custos, 60 medições, Gantt de 40 semanas.",
))

# ============================================================================================ 10
SPECS.append(dict(
    mod="p10_clinica", op=10, categoria="Clínicas", preco=(67, 57, 117),
    comercial="Agenda, Faltas e Retornos para Clínicas", slogan="Menos horários vazios. Mais retornos agendados.",
    dor="Pacientes faltam e a agenda fica vazia; retornos não são reagendados e a receita perdida não é medida.",
    resumo="Agenda com status, confirmações pendentes, taxa de falta por profissional e dia da semana, receita perdida, fila de retornos e valores a receber, sem dados clínicos.",
    para_que=["Organizar a agenda com status (agendado, confirmado, compareceu, faltou, cancelado, remarcado).", "Mostrar quem precisa ser confirmado e quais pacientes precisam de retorno agendado.",
              "Medir a taxa de faltas e a receita perdida por profissional e por dia da semana."],
    publico=["Consultórios e clínicas (odonto, fisioterapia, psicologia, estética)", "Clínicas de nutrição e pilates", "Espaços com agenda por profissional", "Qualquer serviço com hora marcada"],
    antes=["Lista de profissionais.", "Lista de procedimentos com valor e prazo de retorno (dias).", "Convênios atendidos.", "Cadastro mínimo de pacientes (nome, telefone, convênio), sem informações de saúde."],
    abas=[("Início", "Instruções."), ("Config", "Janelas de alerta, mês de análise, profissionais, procedimentos, convênios, pagamentos."), ("Pacientes", "Cadastro mínimo com consultas e faltas."), ("Agenda", "Todos os agendamentos (3.000)."),
          ("Pendências", "Confirmações dos próximos dias e retornos a agendar com telefone."), ("Relatórios", "Taxa de falta, receita perdida, por profissional, por dia da semana e tendência.")],
    passo1=("Configure e cadastre", ["Abra **Config**: **C6** (confirmar agendamentos com até X dias), **C7** (alertar retornos que vencem em X dias) e, se quiser, **C8** o mês de análise (vazio = mês atual).", "Cadastre profissionais (**E5:E14**) e procedimentos com **valor** e **dias para retorno** (**G5:I34**; use 0 para sem retorno), convênios e formas de pagamento.",
                                    "Abra **Pacientes** e cadastre **Código**, **Nome**, **Telefone** e **Convênio**. Não registre informações de saúde."], "img/inicio.png"),
    passo2=("Lance a agenda", ["Abra **Agenda**: **Data**, **Hora**, **Profissional**, **Cód. paciente** (lista), **Procedimento** e **Status**.", "Atualize o status durante o dia: Confirmado, Compareceu, Faltou, Cancelado ou Remarcado.",
                              "Para convênio ou desconto, digite o valor na coluna **Valor cobrado**; ao receber, preencha **Valor recebido** e a **Forma de pagamento**.", "A coluna **ALERTA** indica CONFIRMAR, Atualizar status, Cobrar ou 'Falta: reagendar'."], "img/agenda.png"),
    passo3=("Confirme, recupere retornos e meça", ["Abra **Pendências**: à esquerda quem **confirmar** nos próximos dias; à direita os **retornos a agendar** (com telefone).", "Abra **Relatórios**: agendadas, compareceram, faltaram, **taxa de falta**, **receita realizada** e **receita perdida em faltas**.",
                                                 "Veja a taxa de falta por profissional e por **dia da semana** para decidir onde reforçar a confirmação ou aplicar overbooking responsável."], "img/relatorios.png"),
    indicadores=[("Taxa de falta", "Faltou ÷ (compareceu + faltou). Cancelamentos e remarcações não entram."), ("Receita perdida", "Valor dos atendimentos marcados como 'Faltou'."), ("Ticket médio", "Receita realizada ÷ comparecimentos."),
                 ("Confirmações pendentes", "Agendamentos 'Agendado' dentro da janela de dias da Config."), ("Retornos a agendar", "Pacientes atendidos cujo retorno previsto vence (ou venceu há até 60 dias) e não há consulta futura."), ("A receber", "Atendimentos realizados com valor recebido menor que o valor do atendimento.")],
    exemplo=["Clínica fictícia com 4 profissionais, 46 pacientes e 8 procedimentos; agenda de julho a outubro de 2026; mês de análise: setembro de 2026; hoje = 08/10/2026.",
             "Setembro: **{{Relatórios!A5|int}}** agendadas, **{{Relatórios!C5|int}}** compareceram e **{{Relatórios!E5|int}}** faltaram: taxa de falta de **{{Relatórios!G5|pct}}**, o que representou **{{Relatórios!A8|money}}** de receita perdida.",
             "Receita realizada: **{{Relatórios!I5|money}}** (ticket médio **{{Relatórios!C8|money}}**); a receber: **{{Relatórios!E8|money}}**.",
             "Pendências hoje: **{{Relatórios!G8|int}}** confirmações e **{{Relatórios!I8|int}}** retornos a agendar. No gráfico por dia da semana, a sexta-feira tem a maior taxa de falta."],
    diario=["Confirme os agendamentos de amanhã (aba Pendências).", "Atualize os status do dia e registre os recebimentos."],
    semanal=["Ligue para pacientes de retorno vencendo.", "Veja a taxa de falta da semana por profissional."],
    mensal=["Compare taxa de falta com o mês anterior.", "Reavalie horários e política de cancelamento.", "Revise valores dos procedimentos."],
    erros=[("Deixar agendamentos passados como 'Agendado'", "O alerta 'Atualizar status' avisa; sem corrigir, faltas e receita saem errados."),
           ("Contar cancelamento como falta", "Use 'Cancelado' ou 'Remarcado' quando o paciente avisou; só 'Faltou' sem aviso."),
           ("Código de paciente repetido", "A validação bloqueia códigos repetidos."),
           ("Registrar dados de saúde no campo de observação", "Não faça isso: use apenas observações administrativas (LGPD)."),
           ("Esquecer o prazo de retorno do procedimento", "Sem os dias de retorno na Config, o paciente não entra na fila de retornos.")],
    faq=[("A planilha envia lembretes?", "Não; ela lista quem precisa ser confirmado, com telefone, para você enviar por WhatsApp."),
         ("Posso registrar prontuário?", "Não. A planilha é só de gestão; prontuário exige sistema próprio e regras de sigilo."),
         ("Funciona para convênios?", "Sim: informe o valor do convênio na coluna Valor cobrado e acompanhe a receita por paciente e convênio."),
         ("O que é 'Retornos a agendar'?", "Pacientes que compareceram a um procedimento com prazo de retorno e ainda não têm consulta futura marcada."),
         ("Quantos agendamentos cabem?", "3.000 linhas de agenda e 1.000 pacientes.")],
    vantagens=["Mede o custo das faltas em R$.", "Fila de retornos com telefone.", "Taxa de falta por profissional e dia da semana.", "Sem dados clínicos: mais simples e seguro.", "Sem mensalidade."],
    objecoes=[("Já uso agenda online.", "Muitas não mostram receita perdida nem fila de retornos. Use a planilha para medir e agir."),
              ("Tenho receio de LGPD.", "A planilha foi desenhada para armazenar só dados mínimos de contato. Não registre informações de saúde."),
              ("Pacientes faltam por motivos fora do meu controle.", "A confirmação 48h antes costuma reduzir faltas; e o relatório mostra onde está o problema.")],
    preco_just="Dor com apoio de fornecedores (média) e valor direto: cada falta evitada recupera receita. Complexidade média-alta. Concorrência: softwares de clínica. Premium: pacotes/planos de tratamento e controle de comissão por profissional.",
    kits=["Kit Clínica", "Kit Completo"],
    pitch30="Quanto sua clínica perde por mês com faltas? A planilha de Agenda, Faltas e Retornos calcula a taxa de falta por profissional e dia da semana, mostra a receita perdida, lista quem confirmar e quem precisa de retorno, tudo sem dados clínicos. Tutorial e exemplo inclusos.",
    cap="3.000 agendamentos, 1.000 pacientes, 30 procedimentos, 10 profissionais.",
))
