# -*- coding: utf-8 -*-
"""Conteúdo de documentação e venda dos produtos 01-05.
Placeholders {{Aba!Célula|fmt}} são substituídos por valores reais lidos do EXEMPLO.xlsx (fmt: money, pct, int, n1, txt)."""

SPECS = []

# ============================================================================================ 01
SPECS.append(dict(
    mod="p01_fluxo", op=1, categoria="Financeiro", preco=(47, 37, 87),
    comercial="Fluxo de Caixa Inteligente", slogan="Saiba, de verdade, quanto sobra no fim do mês.",
    dor="O dono não sabe quanto realmente sobra no final do mês nem se o caixa vai aguentar os próximos meses.",
    resumo="Planilha de fluxo de caixa com previsto x realizado, saldo projetado mês a mês, alerta de saldo negativo, meses de reserva e ranking de despesas.",
    para_que=["Registrar todas as entradas e saídas da empresa (já realizadas ou ainda previstas) em um só lugar.",
              "Mostrar o saldo atual, o saldo projetado até dezembro e em qual mês o caixa pode ficar negativo.",
              "Dizer para onde o dinheiro está indo (maiores categorias de saída) e quantos meses de despesas você tem de reserva."],
    publico=["MEIs e autônomos que querem separar pró-labore e lucro", "Lojas, restaurantes, oficinas, clínicas e escritórios pequenos",
             "Prestadores de serviço com receita irregular", "Qualquer empresa que hoje controla o caixa 'pelo extrato do banco'"],
    antes=["Saldo em caixa + bancos no dia 1º de janeiro do ano (ou do dia em que vai começar).", "Extratos bancários e da maquininha do período que quer lançar.",
           "Lista das contas fixas (aluguel, folha, internet...) e das vendas esperadas dos próximos meses (serão lançadas como 'Previsto').",
           "Nome das contas que usa (Caixa, Banco, Maquininha...)."],
    abas=[("Início", "Instruções rápidas e mapa das abas."), ("Config", "Empresa, ano, saldo inicial, meta de reserva, categorias e contas."),
          ("Lançamentos", "Onde você registra cada entrada e saída (1.000 linhas)."), ("Mensal", "Entradas, saídas, resultado, saldo realizado e projetado de cada mês + alerta."),
          ("Dashboard", "Indicadores e gráficos (saldo atual, reserva, maiores saídas).")],
    passo1=("Configure a empresa", ["Abra a aba **Config**.", "Clique na célula **C4** e digite o nome da empresa.", "Em **C5** confirme o ano. Em **C6** digite o saldo inicial (quanto havia em caixa + bancos em 1º de janeiro).",
                                   "Em **C8** informe a meta de reserva: quantos meses de despesas você quer ter guardados (sugestão: 3).",
                                   "Role até a tabela de categorias (**B12:D51**) e ajuste os nomes ao seu negócio. Cada categoria precisa de um **Tipo** (Entrada ou Saída)."], "img/inicio.png"),
    passo2=("Lance as entradas e saídas", ["Abra a aba **Lançamentos** e clique na primeira linha amarela (célula **A5**).", "Preencha, da esquerda para a direita: **Data**, **Tipo** (Entrada/Saída), **Categoria** (lista), **Descrição**, **Conta** (lista), **Valor** e **Status**.",
                                          "Digite o valor **sempre positivo**: a planilha subtrai sozinha quando o Tipo é Saída.", "Use **Realizado** para o que já aconteceu e **Previsto** para o que vai acontecer (conta futura, venda esperada).",
                                          "Olhe a coluna **Conferência**: deve mostrar OK. Se mostrar 'Categoria x Tipo?', você marcou, por exemplo, 'Aluguel' como Entrada."], "img/lancamentos.png"),
    passo3=("Entenda os cálculos", ["Abra a aba **Mensal**: cada linha é um mês do ano.", "**Saldo realizado** = saldo inicial + resultados dos meses (só o que já aconteceu).",
                                   "**Saldo projetado** = saldo realizado + o que está Previsto. É ele que avisa se o caixa vai ficar negativo.", "A coluna **Alerta** mostra OK, 'Mês no vermelho' (gastou mais que recebeu) ou 'SALDO NEGATIVO'.",
                                   "Abra o **Dashboard** para ver tudo em gráficos. Nada precisa ser digitado nessas duas abas."], "img/mensal.png"),
    indicadores=[("Saldo atual", "Dinheiro disponível hoje (saldo inicial + entradas realizadas - saídas realizadas)."), ("Resultado no ano", "Entradas - saídas realizadas. Positivo = sobrou dinheiro."),
                 ("Margem no ano", "Resultado ÷ entradas. Quanto sobra de cada R$ 100 que entra."), ("Saldo projetado (dez)", "Onde o caixa termina o ano se tudo o que está Previsto acontecer."),
                 ("Meses de reserva", "Saldo atual ÷ média mensal de saídas. Abaixo de 1 é crítico; ideal acima da sua meta."), ("Maiores saídas", "As 8 categorias que mais consomem dinheiro: onde cortar primeiro.")],
    exemplo=["Empresa fictícia 'Empresa Exemplo Ltda' (varejo + serviços) com saldo inicial de R$ 18.000,00 e lançamentos de janeiro a dezembro de 2026 (realizados até 08/10/2026; o resto previsto).",
             "Saldo atual: **{{Dashboard!A5|money}}**; entradas realizadas no ano: **{{Dashboard!D5|money}}**; saídas: **{{Dashboard!G5|money}}**; resultado: **{{Dashboard!J5|money}}** (margem de **{{Dashboard!A8|pct}}**).",
             "Meses de reserva: **{{Dashboard!G8|n1}}** → situação: **{{Dashboard!J8|txt}}** (a meta configurada é 3 meses). Saldo projetado em dezembro: **{{Dashboard!D8|money}}**.",
             "Leitura: a empresa fatura bem, mas o fornecedor e a folha consomem mais da metade das saídas e a reserva está curta; o caminho é renegociar compras e formar reserva."],
    diario=["Lance as vendas e pagamentos do dia (ou do dia anterior).", "Troque para 'Realizado' o que foi pago/recebido."],
    semanal=["Confira o saldo do Dashboard com o saldo do banco; se divergir, procure lançamento faltando.", "Lance as contas previstas das próximas semanas."],
    mensal=["Feche o mês: veja Resultado e Margem na aba Mensal.", "Compare as 3 maiores saídas com o mês anterior.", "Revise a meta de reserva."],
    erros=[("Digitar valor negativo nas saídas", "A planilha já subtrai as saídas. Digite sempre valores positivos (a validação bloqueia negativos)."),
           ("Deixar tudo como 'Realizado'", "Contas futuras devem ser 'Previsto', senão o saldo projetado e o alerta ficam errados."),
           ("Categoria incompatível com o Tipo", "A coluna Conferência mostra 'Categoria x Tipo?'. Corrija o Tipo ou a categoria."),
           ("Esquecer o saldo inicial", "Sem ele o saldo fica errado. Preencha Config!C6 com o saldo de 1º de janeiro."),
           ("Alterar o ano e esperar dados antigos", "O ano da Config filtra todo o relatório. Para outro ano, use uma cópia da planilha limpa."),
           ("Escrever datas como texto", "Use dd/mm/aaaa. Datas inválidas são recusadas pela validação.")],
    faq=[("Posso usar no Google Sheets?", "Sim, mas recomendamos Excel (ou LibreOffice). No Google Sheets alguns formatos de gráfico podem mudar; os cálculos funcionam."),
         ("Quantos lançamentos cabem?", "1.000 linhas por ano (mais que suficiente para a maioria das pequenas empresas). Para mais, use uma cópia por semestre."),
         ("Posso ter mais de uma conta bancária?", "Sim. Cadastre as contas em Config (F12:F23) e escolha em cada lançamento. O saldo é o total de todas."),
         ("E o pró-labore do dono?", "Há a categoria 'Pró-labore / retiradas'. Lance como Saída; assim você separa o salário do dono do lucro da empresa."),
         ("A planilha emite nota fiscal ou concilia banco?", "Não. Ela é um controle gerencial: você lança manualmente e confere com o extrato.")],
    vantagens=["Previsto x Realizado: enxerga o futuro, não só o passado.", "Alerta automático de saldo negativo e de meses no vermelho.", "Meses de reserva: o indicador que quase ninguém acompanha.",
               "Conferência automática de lançamentos (categoria x tipo).", "Dashboard pronto, sem fórmulas para montar."],
    objecoes=[("Já uso o aplicativo do banco.", "O app mostra o que passou. A planilha mostra o que vai acontecer e para onde o dinheiro vai, por categoria."),
              ("Tenho pouco tempo.", "O lançamento leva 5 minutos por dia e o Guia Rápido faz você começar em 5 minutos."),
              ("Planilha grátis tem na internet.", "As grátis são tabelas. Esta traz previsto x realizado, alertas, meses de reserva, dashboard, tutorial e exemplo preenchido."),
              ("Não entendo de finanças.", "O Tutorial explica cada indicador em linguagem simples com um exemplo completo.")],
    preco_just="Preço de entrada: é a planilha que quase todo cliente compra primeiro. Complexidade média (5 abas, previsto x realizado), alto valor gerado (evita juros e multas) e muitos concorrentes gratuitos, por isso o foco é o pacote completo (tutorial + exemplo). A versão premium inclui multiempresa/centros de custo e metas por categoria.",
    kits=["Kit Pequeno Empresário", "Kit Loja", "Kit Restaurante", "Kit Oficina", "Kit Construtora", "Kit Clínica", "Kit Comercial e Serviços", "Kit Completo"],
    pitch30="Você sabe quanto vai sobrar no fim do mês? Com o Fluxo de Caixa Inteligente você lança entradas e saídas, separa o que já aconteceu do que ainda vai acontecer e vê o saldo de cada mês até dezembro. Se o caixa for ficar negativo, a planilha avisa antes. Vem com tutorial, exemplo preenchido e dashboard.",
    cap="1.000 lançamentos por ano, 40 categorias, 12 contas.",
))

# ============================================================================================ 02
SPECS.append(dict(
    mod="p02_precificador", op=2, categoria="Precificação", preco=(57, 47, 97),
    comercial="Precificador de Produtos e Serviços", slogan="Preço certo, lucro garantido.",
    dor="O empresário define o preço por intuição ou copiando a concorrência: vende muito e não sobra lucro, e confunde markup com margem.",
    resumo="Calcula o preço de venda de produtos e serviços com custo, impostos, comissão, taxas, despesas fixas e lucro desejado; avisa itens em prejuízo e simula descontos.",
    para_que=["Calcular o preço de cada produto e serviço para garantir o lucro que você quer, depois de pagar impostos, comissão, taxa de cartão e as despesas fixas.",
              "Mostrar quais itens vendidos hoje dão prejuízo ou estão abaixo do ideal.", "Simular descontos: quanto cai o lucro e quanto você precisa vender a mais para compensar."],
    publico=["Lojas e e-commerce", "Prestadores de serviço (instalação, manutenção, consultoria)", "Confeiteiras, artesãos e pequenas indústrias", "MEIs e autônomos que cobram 'no olho'"],
    antes=["Custo de compra ou produção de cada produto (e frete/embalagem por unidade).", "Percentual médio de impostos sobre a venda (pergunte ao contador).", "Comissão paga a vendedores e taxa média de cartão/marketplace.",
           "Soma dos custos fixos mensais (aluguel, salários, energia...) e o faturamento médio mensal.", "Para serviços: pró-labore desejado e horas realmente vendáveis por mês."],
    abas=[("Início", "Instruções."), ("Config", "Impostos, comissão, taxa, lucro desejado, custos fixos, custo da hora."), ("Produtos", "Cadastro com custo, preço sugerido, margem real e status (300 itens)."),
          ("Serviços", "Preço por serviço com horas, materiais e custo da hora (100 itens)."), ("Simulador", "Efeito de descontos no lucro e nas vendas necessárias."), ("Resumo", "Contagem de itens em prejuízo, margem média e gráfico.")],
    passo1=("Preencha a Config", ["Abra a aba **Config**.", "Em **C6** digite o imposto sobre vendas (ex.: 6%). Em **C7** a comissão. Em **C8** a taxa de pagamento/plataforma. Em **C9** o lucro líquido desejado (ex.: 20%).",
                                  "Em **C12** informe os custos fixos mensais e em **C13** o faturamento médio mensal. A planilha calcula o rateio de despesa fixa em **C14**.",
                                  "Para serviços: **C17** pró-labore desejado e **C18** horas produtivas por mês. O custo da hora aparece em **C19**."], "img/inicio.png"),
    passo2=("Cadastre produtos e serviços", ["Abra **Produtos** e preencha nas colunas amarelas: Código, Produto, Categoria, **Custo de compra/produção** e **Frete/embalagem**.",
                                           "Percentuais específicos (imposto, comissão, taxa, lucro) são opcionais: **deixe em branco para usar o padrão** da Config; digite 0% se o item não tem aquele custo.",
                                           "Se já vende o produto, digite o **Preço que pratico hoje** (coluna K) para ver margem e status. Opcional: preço do concorrente (J).",
                                           "Em **Serviços**, informe horas gastas, materiais e deslocamento; o custo da mão de obra vem do custo da hora."], "img/produtos.png"),
    passo3=("Leia o preço e simule descontos", ["Em **Produtos**, a coluna **PREÇO SUGERIDO** (verde) é o preço que garante o lucro desejado. **Preço mínimo** é o menor preço com lucro zero.",
                                              "A coluna **Status** mostra PREJUÍZO, Abaixo do ideal ou OK conforme o preço que você pratica.", "Abra **Simulador**, escolha o produto em **C4** e digite o desconto em **C5**.",
                                              "Veja o lucro por unidade antes e depois e a linha **Vendas a mais para manter o MESMO lucro total**. Abra o **Resumo** para o panorama."], "img/simulador.png"),
    indicadores=[("Preço calculado", "Custo total ÷ (1 - soma dos percentuais). É o preço exato."), ("Preço sugerido", "Preço calculado arredondado para terminar em ,90 (preço psicológico)."), ("Markup", "Preço sugerido ÷ custo. Quantas vezes o custo é multiplicado."),
                 ("Margem líquida no preço atual", "Quanto sobra de lucro por R$ 100 vendidos ao preço que pratica."), ("Status", "PREJUÍZO = lucro negativo; Abaixo do ideal = lucra, mas menos que o desejado; OK = bate a meta."),
                 ("Vendas a mais necessárias", "Quanto precisa vender além do atual para ter o mesmo lucro total depois de dar desconto.")],
    exemplo=["Loja fictícia com imposto de 6%, comissão de 3%, taxa de 3,5%, lucro desejado de 20% e rateio de despesa fixa de 23,3% (custos fixos de R$ 14 mil sobre faturamento de R$ 60 mil). Os 24 produtos do exemplo mostram o status de cada preço.",
             "Itens cadastrados: **{{Resumo!A5|int}}**; em prejuízo: **{{Resumo!C5|int}}**; abaixo do ideal: **{{Resumo!E5|int}}**; com preço OK: **{{Resumo!G5|int}}**. Margem média atual: **{{Resumo!A8|pct}}** (desejada: {{Resumo!C8|pct}}).",
             "Primeiro produto: preço exato **{{Produtos!N5|money}}**, sugerido **{{Produtos!O5|money}}**. Custo da hora dos serviços: **{{Resumo!G8|money}}**.",
             "Simulador (produto **{{Simulador!C4|txt}}**, desconto de 10%): lucro por unidade cai de **{{Simulador!C11|money}}** para **{{Simulador!C13|money}}**; é preciso vender **{{Simulador!C15|pct}}** a mais para manter o lucro total."],
    diario=["Nada obrigatório. Use ao precificar um item novo ou ao negociar um desconto."],
    semanal=["Atualize o preço de compra dos itens que mudaram de fornecedor.", "Revise os itens com status PREJUÍZO."],
    mensal=["Atualize custos fixos e faturamento médio na Config (o rateio muda).", "Reveja impostos e taxas.", "Compare os preços sugeridos com a concorrência."],
    erros=[("Usar percentuais sobre o custo em vez de sobre o preço", "Todos os percentuais são sobre o PREÇO DE VENDA. Se seu imposto é 6% do faturamento, digite 6%."),
           ("Esquecer de incluir o frete e a embalagem", "Preencha a coluna 'Frete/embalagem por un.' para o custo total ficar correto."),
           ("Aparecer 'Revisar %'", "A soma dos percentuais chegou a 100% ou mais; reduza custos fixos, lucro desejado ou taxas."),
           ("Colocar o faturamento errado na Config", "Se o faturamento for menor que o real, o rateio fixo fica alto demais e os preços sobem; use a média dos últimos 6 meses."),
           ("Digitar 0 achando que é 'padrão'", "Em branco = usa o padrão. Digitar 0% = o item não tem esse custo.")],
    faq=[("Qual a diferença entre markup e margem?", "Markup é sobre o custo (preço ÷ custo - 1). Margem é sobre o preço (lucro ÷ preço). A planilha mostra os dois."),
         ("Serve para vender em marketplace?", "Sim: use a Taxa de pagamento/plataforma como a comissão do marketplace e coloque o frete subsidiado na coluna de frete/embalagem. Uma versão premium com tabelas por canal está no roadmap."),
         ("Preciso saber contabilidade?", "Não. O Tutorial explica cada campo e o contador informa o percentual de impostos."),
         ("Como calcular o custo da hora?", "A planilha calcula: (custos fixos + pró-labore) ÷ horas produtivas por mês."),
         ("Posso mudar o arredondamento do preço?", "O preço sugerido termina em ,90. Se preferir outro, use o preço calculado (coluna N) como base.")],
    vantagens=["Produtos e serviços na mesma planilha.", "Simulador de desconto com 'vendas a mais necessárias': o argumento que convence o dono a não dar desconto sem pensar.", "Percentuais por item com padrão automático.",
               "Semáforo de margem sobre o preço que você pratica hoje.", "Rateio automático da despesa fixa."],
    objecoes=[("Meu preço é o do mercado.", "O preço do mercado só vale se cobrir o seu custo e lucro. A planilha mostra se você está perdendo dinheiro em cada venda."),
              ("Tem calculadora grátis.", "Calculadoras fazem um produto por vez. Aqui você tem o catálogo inteiro, status de prejuízo e simulador de desconto."),
              ("Meus custos mudam toda hora.", "É só atualizar o custo do item: preço sugerido, margem e status recalculam sozinhos.")],
    preco_just="Precificação é a dor mais citada pelo Sebrae e o ganho é imediato (cada item mal precificado perde dinheiro em toda venda), por isso o valor percebido é alto. Complexidade média; concorrência gratuita em calculadoras simples. Premium: tabela de taxas por marketplace (Mercado Livre, Shopee, Amazon, Magalu) e margem por canal.",
    kits=["Kit Pequeno Empresário", "Kit Loja", "Kit Restaurante", "Kit Comercial e Serviços", "Kit Completo"],
    pitch30="Você sabe se o preço que cobra dá lucro? O Precificador calcula o preço de cada produto e serviço com impostos, comissão, taxa de cartão, despesas fixas e o lucro que você quer, mostra quais itens dão prejuízo e simula quanto custa dar desconto. Tutorial e exemplo prontos.",
    cap="300 produtos e 100 serviços.",
))

# ============================================================================================ 03
SPECS.append(dict(
    mod="p03_estoque", op=3, categoria="Estoque", preco=(67, 57, 117),
    comercial="Estoque Inteligente com Curva ABC", slogan="Falta zero do que vende. Sobra zero do que não vende.",
    dor="Falta do que vende e excesso do que não vende: dinheiro parado em estoque e vendas perdidas por ruptura.",
    resumo="Controle de estoque com entradas e saídas, status (ruptura/repor/ok/excesso), itens parados, lista de compras por fornecedor e Curva ABC automática com gráfico de Pareto.",
    para_que=["Saber o estoque atual de cada item sem contar prateleira.", "Ser avisado do que precisa repor, do que está em excesso e do que está parado há meses.",
              "Montar a lista de compras e descobrir quais itens (classe A) pagam as contas da empresa."],
    publico=["Lojas físicas e e-commerce", "Papelarias, farmácias, autopeças, mercadinhos", "Distribuidores pequenos", "Qualquer negócio que compra para revender"],
    antes=["Lista de produtos com código, custo e preço de venda.", "Contagem física do estoque de hoje (será o estoque inicial).", "Estoque mínimo de cada item (quanto dura até o fornecedor entregar).",
           "Fornecedor principal de cada item e histórico de vendas, se existir."],
    abas=[("Início", "Instruções."), ("Config", "Período de análise, estoque máximo, cortes ABC, categorias, unidades, fornecedores."), ("Produtos", "Cadastro de até 300 itens."),
          ("Movimentações", "Entradas e saídas (3.000 linhas)."), ("Posição", "Estoque atual, status, cobertura, parado, sugestão de compra."), ("Curva ABC", "Ranking por faturamento e classes A/B/C."),
          ("Compras", "Lista de compras com total."), ("Dashboard", "Indicadores, situação, top 15.")],
    passo1=("Configure e cadastre os produtos", ["Abra **Config**: em **C6** o período para medir vendas (padrão 90 dias), em **C7** os dias sem saída para considerar 'Parado', em **C8** o fator do estoque máximo (2 = dobro do mínimo).",
                                               "Cadastre categorias (**E5:E34**), unidades (**F5:F34**) e fornecedores (**G5:G34**).", "Abra **Produtos** e preencha: **Código** (único), Produto, Categoria, Unidade, Fornecedor, **Custo**, **Preço de venda**, **Estoque inicial** (contagem de hoje) e **Estoque mínimo**."], "img/inicio.png"),
    passo2=("Lance as movimentações", ["Abra **Movimentações**. Cada linha é um movimento: **Data**, **Código** (lista), **Tipo** (Entrada ou Saída) e **Quantidade**.", "Entrada = compra, devolução de cliente. Saída = venda, perda, consumo interno.",
                                      "Observação opcional: número da NF ou pedido.", "A coluna **Alerta** deve mostrar OK; 'Código inválido' significa que o código não está em Produtos."], "img/posicao.png"),
    passo3=("Leia a Posição, a Curva ABC e a lista de compras", ["Abra **Posição**: **ESTOQUE ATUAL** e **STATUS** (RUPTURA = zerado; REPOR = no mínimo ou abaixo; EXCESSO = acima do máximo; OK).",
                                                               "A coluna **Parado?** marca itens com estoque e sem saída há mais do período definido; **Valor parado** soma o dinheiro empatado.", "Abra **Curva ABC**: classe A = poucos itens com ~80% do faturamento; B até 95%; C o resto.",
                                                               "Abra **Compras**: itens em RUPTURA/REPOR com fornecedor, quantidade sugerida e total em R$. Abra o **Dashboard** para o resumo."], "img/curva-abc.png"),
    indicadores=[("Estoque atual", "Estoque inicial + entradas - saídas."), ("Cobertura (dias)", "Estoque atual ÷ média diária de saídas. Quantos dias o estoque dura."), ("Valor em estoque", "Estoque atual x custo unitário."),
                 ("Dinheiro parado", "Valor em estoque dos itens sem saída há muito tempo."), ("Classe A/B/C", "A = itens que mais faturam (prioridade); C = pouco faturamento (compre pouco)."), ("Compra sugerida", "Quantidade para chegar ao estoque máximo, x custo.")],
    exemplo=["Papelaria fictícia com 40 produtos e cerca de 700 movimentações entre julho e outubro de 2026.",
             "Valor em estoque: **{{Dashboard!C5|money}}**. Itens em ruptura: **{{Dashboard!E5|int}}**; para repor: **{{Dashboard!G5|int}}**; em excesso: **{{Dashboard!I5|int}}**.",
             "Itens parados: **{{Dashboard!A8|int}}** somando **{{Dashboard!C8|money}}** de dinheiro parado. Itens classe A: **{{Dashboard!G8|int}}**.",
             "Lista de compras sugerida: **{{Dashboard!I8|money}}** (itens em ruptura/reposição, até o estoque máximo)."],
    diario=["Lance as vendas e entradas do dia (ou use o fechamento do caixa).", "Confira a aba Compras antes de falar com fornecedores."],
    semanal=["Revise itens em RUPTURA e REPOR.", "Faça contagem de uma categoria (inventário rotativo) e corrija diferenças com uma movimentação."],
    mensal=["Veja a Curva ABC e os itens Parados: promoção, kit ou devolução ao fornecedor.", "Ajuste estoque mínimo dos itens classe A."],
    erros=[("Código diferente entre Produtos e Movimentações", "Escolha o código pela lista suspensa. 'Código inválido' no Alerta indica o erro."),
           ("Esquecer de lançar vendas", "O estoque só cai com lançamentos de Saída. Lance diariamente ou importe o relatório do caixa."),
           ("Estoque inicial errado", "Faça a contagem física antes. Diferenças futuras podem ser ajustadas com uma Entrada/Saída com observação 'Ajuste de inventário'."),
           ("Estoque mínimo em branco", "Sem mínimo o item nunca aparece como REPOR nem tem estoque máximo. Preencha o mínimo."),
           ("Esperar Curva ABC sem vendas", "A classe depende das saídas dentro do período da Config; sem saídas todos viram C.")],
    faq=[("Dá para usar com código de barras?", "Sim, use o código de barras como Código do produto (texto ou número, mas sempre igual nas duas abas)."),
         ("Quantos produtos e movimentações?", "300 produtos e 3.000 movimentações. Para mais, mantenha uma cópia por semestre."),
         ("O estoque máximo é calculado?", "Sim: estoque mínimo x fator da Config (padrão 2)."),
         ("Posso ter mais de um depósito?", "Não nesta versão; use uma cópia por depósito. Multi-depósito está planejado para a versão premium."),
         ("Como a classe ABC é calculada?", "Faturamento do período = saídas x preço de venda (ou custo se não houver preço). Ordenado do maior ao menor; A até 80% acumulado, B até 95%.")],
    vantagens=["Curva ABC automática, sem macros e sem ordenar nada.", "Status e lista de compras prontos para enviar ao fornecedor.", "Itens parados com valor imobilizado em R$.", "Cobertura em dias de cada item.", "Validação de códigos e alertas de lançamento."],
    objecoes=[("Meu sistema já controla estoque.", "Muitos sistemas não mostram Curva ABC, itens parados nem lista de compras pronta. Use a planilha como painel de decisão."),
              ("Tenho muitos itens.", "Comece pelos 50 itens classe A (os que mais vendem) e expanda."),
              ("Dá trabalho lançar tudo.", "Se você já registra vendas, copie o relatório diário; o lançamento é uma linha por item por dia.")],
    preco_just="Planilha mais completa da primeira leva (8 abas, ABC, lista de compras). Dinheiro parado em estoque costuma superar o preço da planilha em dias; planilhas gratuitas de estoque raramente trazem ABC e status. Premium: multi-depósito e inventário por contagem.",
    kits=["Kit Loja", "Kit Restaurante", "Kit Oficina", "Kit Completo"],
    pitch30="Seu dinheiro está parado na prateleira? O Estoque Inteligente mostra o estoque de cada item, avisa o que repor, monta a lista de compras com o valor total, identifica o que está parado e classifica seus produtos na Curva ABC. Tudo automático, com tutorial e exemplo.",
    cap="300 produtos, 3.000 movimentações, 80 itens na lista de compras.",
))

# ============================================================================================ 04
SPECS.append(dict(
    mod="p04_contas", op=4, categoria="Financeiro", preco=(57, 47, 97),
    comercial="Contas a Pagar e Receber com Inadimplência", slogan="Nenhum vencimento esquecido. Nenhum cliente sem cobrança.",
    dor="Contas vencem sem ninguém ver, clientes atrasam sem cobrança organizada e a inadimplência corrói o caixa.",
    resumo="Controle de contas a pagar e a receber com status automático, multa e juros, aging, ranking de devedores, mensagem de cobrança pronta e previsão de 8 semanas.",
    para_que=["Saber o que vence hoje, o que está vencido e quanto cada cliente deve.", "Calcular multa e juros dos atrasados e já ter o texto da cobrança pronto para enviar.", "Prever semana a semana quanto vai entrar e sair para não ser pego de surpresa."],
    publico=["Prestadores de serviço com contratos mensais", "Escolas, academias e clínicas com mensalidades", "Distribuidores e lojas que vendem a prazo", "Qualquer empresa que paga fornecedores a prazo"],
    antes=["Lista de contas a receber em aberto (cliente, vencimento, valor).", "Lista de contas a pagar em aberto (fornecedor, vencimento, valor).", "Percentual de multa e juros do seu contrato (comum: 2% e 1% ao mês).", "Telefone dos clientes (para a cobrança)."],
    abas=[("Início", "Instruções."), ("Config", "Multa, juros, dias de alerta, clientes, fornecedores, categorias, formas de pagamento."), ("Receber", "Contas a receber com status, atraso, multa/juros e mensagem de cobrança."),
          ("Pagar", "Contas a pagar com status e ação."), ("Painel", "Indicadores, aging, maiores devedores e previsão de 8 semanas.")],
    passo1=("Configure e cadastre clientes e fornecedores", ["Abra **Config**: **C6** multa (ex.: 2%), **C7** juros ao mês (ex.: 1%), **C8** dias de alerta para pagar (ex.: 7).", "Cadastre clientes com telefone em **E5:F104** e fornecedores em **H5:H64**.",
                                                           "Ajuste categorias de despesa (**J5:J34**) e formas de pagamento (**L5:L16**)."], "img/inicio.png"),
    passo2=("Lance receber e pagar", ["Abra **Receber**: preencha **Cliente** (lista), **Descrição**, **Emissão**, **Vencimento** e **Valor**.", "Quando o cliente pagar, preencha **Data do pagamento**, **Valor pago** e **Forma**. Pagamento parcial? Digite um valor menor: o saldo continua em aberto.",
                                    "Abra **Pagar** e faça o mesmo: **Fornecedor**, **Categoria**, **Vencimento**, **Valor**; ao pagar, data e valor pago.", "As colunas cinza calculam Status, dias de atraso, faixa, saldo, multa e juros e a ação a tomar."], "img/receber.png"),
    passo3=("Cobre e planeje", ["Em **Receber**, filtre o Status 'Vencido' e copie a coluna **Mensagem de cobrança** (WhatsApp).", "Em **Pagar**, filtre 'Vencida' e 'Vence em breve' para priorizar pagamentos.",
                               "Abra o **Painel**: inadimplência, aging por faixa, maiores devedores com telefone e a previsão das próximas 8 semanas (saldo acumulado em vermelho = faltará dinheiro)."], "img/painel.png"),
    indicadores=[("Inadimplência (% do aberto)", "Vencido a receber ÷ total a receber em aberto."), ("Aging", "Valor em aberto por faixa de atraso: quanto mais antigo, menor a chance de receber."), ("Maiores devedores", "Os 5 clientes com mais valor em atraso."),
                 ("A pagar nos próximos dias", "Soma das contas a pagar que vencem dentro dos dias de alerta."), ("Saldo acumulado (previsão)", "Receber - pagar semana a semana. Negativo = precisará de dinheiro.")],
    exemplo=["Empresa fictícia de serviços com 20 clientes e 8 fornecedores, com contas de junho a dezembro de 2026 (hoje = 08/10/2026).",
             "A receber em aberto: **{{Painel!A5|money}}**, dos quais **{{Painel!D5|money}}** vencidos → inadimplência de **{{Painel!G5|pct}}**.",
             "A pagar em aberto: **{{Painel!A8|money}}**; vencido a pagar: **{{Painel!D8|money}}**; vencem nos próximos 7 dias: **{{Painel!G8|money}}**.",
             "Cliente que mais deve: **{{Painel!G12|txt}}** com **{{Painel!J12|money}}** em atraso."],
    diario=["Registre pagamentos e recebimentos do dia.", "Envie as cobranças de quem venceu ontem e lembretes de quem vence hoje."],
    semanal=["Revise o Painel: aging e previsão das próximas semanas.", "Programe os pagamentos da semana."],
    mensal=["Lance as contas fixas do mês seguinte.", "Negocie ou proteste (com assessoria jurídica) os atrasados acima de 60 dias.", "Reveja o limite de prazo para clientes com atraso recorrente."],
    erros=[("Deixar de preencher a data de pagamento", "Sem a data e o valor pago a conta continua 'Vencida'. Preencha ao receber/pagar."),
           ("Cliente digitado diferente do cadastro", "Use a lista suspensa. Nomes diferentes quebram o ranking de devedores."),
           ("Esperar que juros sejam exatos do contrato", "A planilha usa multa fixa + juros pro rata por dia sobre o saldo. Confira o seu contrato."),
           ("Esquecer de conferir a data de hoje", "Na versão limpa a data é automática (HOJE). Se a planilha parecer 'parada', confira a data do computador."),
           ("Lançar parcelas como uma só conta", "Lance uma linha por parcela, cada uma com seu vencimento.")],
    faq=[("A planilha envia a mensagem sozinha?", "Não. Ela monta o texto pronto; você copia e envia por WhatsApp ou e-mail."),
         ("Funciona com boleto e Pix?", "Sim, só registre a forma de pagamento. Não há integração bancária."),
         ("Posso cobrar juros compostos?", "Esta versão calcula juros simples pro rata. Juros compostos podem ser tema da versão premium."),
         ("Quantas contas cabem?", "1.000 linhas em Receber e 1.000 em Pagar."),
         ("Substitui um sistema de cobrança?", "Não. É um controle simples e visual, ideal para quem ainda cobra manualmente.")],
    vantagens=["Mensagem de cobrança pronta.", "Ranking de maiores devedores com telefone.", "Aging com gráfico.", "Previsão de 8 semanas de entradas e saídas.", "Alertas de contas a pagar para evitar multa."],
    objecoes=[("Meu banco já avisa vencimentos.", "O banco avisa só boletos dele. A planilha reúne todas as contas, inclusive as que não são boleto, e prevê o saldo."),
              ("Tenho poucos clientes.", "Mesmo com 10 clientes, um atraso de 30 dias pode comprometer o caixa do mês."),
              ("Não gosto de cobrar.", "A mensagem pronta e educada facilita; e o aging mostra quem merece atenção primeiro.")],
    preco_just="Dor com dados fortes (inadimplência recorde no Serasa) e uso diário. Complexidade alta (aging, ranking, previsão). Concorrência grátis é de listas simples de contas. Premium: régua de cobrança (lembretes D-3, D0, D+3, D+7) e conciliação de extrato por colagem.",
    kits=["Kit Pequeno Empresário", "Kit Loja", "Kit Restaurante", "Kit Oficina", "Kit Construtora", "Kit Clínica", "Kit Comercial e Serviços", "Kit Completo"],
    pitch30="Quanto seus clientes estão te devendo agora? O Contas a Pagar e Receber mostra o que venceu, calcula multa e juros, entrega a mensagem de cobrança pronta, ranqueia os maiores devedores e prevê o saldo das próximas 8 semanas. Chega de multa por esquecimento.",
    cap="1.000 contas a receber, 1.000 contas a pagar, 100 clientes, 60 fornecedores.",
))

# ============================================================================================ 05
SPECS.append(dict(
    mod="p05_crm", op=5, categoria="Vendas", preco=(67, 57, 117),
    comercial="CRM e Funil de Vendas com Follow-up", slogan="Nenhum lead esquecido. Nenhuma venda perdida por falta de retorno.",
    dor="Leads esfriam por falta de follow-up; oportunidades 'somem' entre WhatsApp, e-mail e papel.",
    resumo="CRM em planilha com funil por etapas, agenda de follow-up diária, previsão ponderada de vendas, conversão por origem, ranking e metas de vendedores.",
    para_que=["Cadastrar leads e acompanhá-los por etapa do funil até ganhar ou perder.", "Mostrar todo dia quem precisa de contato (hoje ou atrasado) para não deixar nenhuma venda esfriar.",
              "Prever vendas (valor ponderado pela probabilidade) e medir conversão por origem e por vendedor."],
    publico=["Equipes comerciais pequenas", "Consultores, corretores e prestadores de serviço", "Lojas e agências com vendas consultivas", "Donos que vendem pelo WhatsApp"],
    antes=["Lista dos leads atuais (nome, contato, origem, valor potencial, etapa).", "Lista de vendedores e a meta mensal de cada um.", "Suas etapas de venda (padrão: Novo, Contato feito, Proposta enviada, Negociação).", "Origens dos leads (indicação, Instagram, Google...)."],
    abas=[("Início", "Instruções."), ("Config", "Etapas e probabilidades, origens, vendedores/metas, motivos de perda."), ("Leads", "Cadastro e acompanhamento (1.000 leads)."),
          ("Agenda", "Follow-ups de hoje e atrasados."), ("Funil", "Leads por etapa, conversão por origem, motivos de perda."), ("Vendedores", "Ranking, meta e conversão."), ("Dashboard", "Indicadores e vendas por mês.")],
    passo1=("Configure o funil e a equipe", ["Abra **Config**. Em **B10:C15** ajuste as etapas e a **probabilidade** de fechamento de cada uma (não renomeie *Ganho* e *Perdido*).", "Cadastre origens (**E5:E14**), vendedores e **meta mensal** (**G5:H14**) e motivos de perda (**J5:J14**).",
                                           "Em **C6** defina quantos dias sem contato geram alerta."], "img/inicio.png"),
    passo2=("Cadastre e atualize os leads", ["Abra **Leads**. Em cada linha: **Data de entrada**, **Lead**, **Contato**, **Origem**, **Vendedor**, **Etapa** e **Valor potencial**.", "Sempre que falar com o lead, atualize **Último contato** e **Próximo follow-up** (a data em que vai procurá-lo).",
                                            "Ao fechar, mude a **Etapa** para Ganho ou Perdido e preencha **Data de fechamento** (e **Motivo da perda**).", "A coluna **FOLLOW-UP** mostra ATRASADO, HOJE, Em dia ou Definir data."], "img/leads.png"),
    passo3=("Trabalhe pela Agenda e leia os relatórios", ["Todo dia abra a aba **Agenda**: ela lista só quem está ATRASADO, é HOJE ou está sem data definida.", "Abra **Funil** para ver leads por etapa, **conversão por origem** e motivos de perda.",
                                                        "Abra **Vendedores** para o ranking e % da meta do mês. O **Dashboard** reúne previsão ponderada, vendido no mês, conversão e ticket médio."], "img/agenda.png"),
    indicadores=[("Valor ponderado", "Valor potencial x probabilidade da etapa. Previsão realista do que deve fechar."), ("Conversão", "Ganhos ÷ (ganhos + perdidos)."), ("Ticket médio", "Valor médio das vendas ganhas."),
                 ("Ciclo médio de venda", "Dias entre a entrada do lead e o fechamento das vendas ganhas."), ("% da meta", "Vendido no mês ÷ meta do vendedor."), ("Follow-ups atrasados", "Leads abertos com próximo contato vencido.")],
    exemplo=["Consultoria fictícia com 64 leads e 4 vendedores (Vendedor A a D), metas mensais de R$ 78 mil no total; data de hoje 08/10/2026.",
             "Leads em aberto: **{{Dashboard!A5|int}}** (**{{Dashboard!C5|money}}**); previsão ponderada: **{{Dashboard!E5|money}}**; vendido no mês: **{{Dashboard!G5|money}}** (**{{Dashboard!A8|pct}}** da meta).",
             "Conversão: **{{Dashboard!C8|pct}}**; ticket médio: **{{Dashboard!E8|money}}**; ciclo médio: **{{Dashboard!G8|n1}}** dias; follow-ups atrasados: **{{Dashboard!I8|int}}**.",
             "Leitura: na aba Funil compare a conversão de cada origem para decidir onde investir, e zere os follow-ups atrasados da Agenda antes de buscar novos leads."],
    diario=["Abra a Agenda e faça os contatos de HOJE e ATRASADOS.", "Atualize Último contato e Próximo follow-up de cada lead trabalhado."],
    semanal=["Revise leads em 'Proposta enviada' e 'Negociação' parados há mais de 7 dias.", "Veja o ranking de vendedores."],
    mensal=["Feche o mês: vendido x meta; conversão por origem.", "Analise os motivos de perda e ajuste a oferta.", "Atualize as metas."],
    erros=[("Não preencher o próximo follow-up", "Sem data, o lead aparece como 'Definir data' ou ATRASADO. Sempre agende o próximo contato."),
           ("Ganhar um lead sem data de fechamento", "A venda não entra no relatório do mês. Preencha a data de fechamento (a coluna Conferência avisa)."),
           ("Renomear Ganho/Perdido", "A planilha usa esses nomes nos cálculos. Renomeie só as outras etapas."),
           ("Valor potencial vazio", "A previsão ponderada fica zerada. Estime sempre um valor."),
           ("Vendedor fora da lista", "Use a lista suspensa; o ranking considera só os vendedores da Config.")],
    faq=[("Substitui um CRM com WhatsApp integrado?", "Não integra com WhatsApp. É ideal para quem quer organizar o funil sem mensalidade."),
         ("Posso ter mais etapas?", "Há 6 etapas na Config (4 abertas + Ganho + Perdido). Você pode renomear as 4 abertas."),
         ("Quantos leads cabem?", "1.000. Mantenha uma cópia por ano."),
         ("A probabilidade é automática?", "Não: você define em Config. Ajuste com o seu histórico de fechamento."),
         ("Posso usar em equipe?", "Sim, em uma pasta compartilhada (Drive, OneDrive); cuide para dois usuários não editarem ao mesmo tempo em arquivo local.")],
    vantagens=["Agenda automática de follow-up.", "Previsão ponderada de vendas.", "Conversão por origem: mostra onde investir.", "Ranking e metas por vendedor.", "Funciona offline, sem mensalidade."],
    objecoes=[("Já tenho CRM.", "Se ele fica abandonado, a planilha é mais simples de manter. Use para provar o processo antes de pagar mensalidade."),
              ("Minha equipe não vai usar.", "A Agenda do dia é uma aba só. Quem usa por 1 semana percebe que esquecer leads acabou."),
              ("Vendo só por WhatsApp.", "Copie o contato e o valor para a planilha; o importante é registrar e agendar o próximo passo.")],
    preco_just="CRMs pagos custam centenas de reais por ano; a planilha entrega o essencial por pagamento único. Complexidade alta e dado de apoio de fornecedores (evidência média), por isso preço intermediário. Premium: propostas com número, comissão por faixa e histórico de interações.",
    kits=["Kit Comercial e Serviços", "Kit Completo"],
    pitch30="Quantos leads você deixou esfriar este mês? O CRM e Funil de Vendas mostra todo dia quem você precisa procurar, prevê suas vendas pela probabilidade de cada etapa, mostra de onde vêm os clientes que fecham e acompanha a meta de cada vendedor. Sem mensalidade.",
    cap="1.000 leads, 10 vendedores, 10 origens.",
))
