# -*- coding: utf-8 -*-
"""Base de oportunidades de produto (dores reais -> planilhas).

Cada oportunidade tem 7 sub-notas (soma = nota 0-100):
  dor(30) frequência de uso(15) mercado(15) valor/dinheiro envolvido(15)
  facilidade de explicar(10) diferencial vs. gratuito(10) viabilidade em planilha(5)

As evidências vêm de buscas na web feitas em out/2026. A "força" indica a qualidade da
evidência: Alta (dado de órgão/instituto ou vários estudos), Média (estudo ou artigo
técnico + convergência de fontes) e Fraca (apenas conteúdo de fornecedores ou nenhuma
fonte quantitativa: validar com clientes antes de produzir).
"""

CRITERIOS = [
    ("Dor comprovada", 30), ("Frequência de uso", 15), ("Tamanho do mercado", 15),
    ("Valor / dinheiro envolvido", 15), ("Facilidade de explicar", 10),
    ("Diferencial vs. gratuitos", 10), ("Viabilidade em planilha", 5),
]

U_FECHAMENTO = "https://www.meucontadoronline.com.br/blog/motivos-de-fechamento-de-pequenas-empresas/"
U_FLUXO = "https://www.meucontadoronline.com.br/blog/fluxo-de-caixa/"
U_LOCOMOTIVA = "https://www.contabeis.com.br/noticias/71830/ma-gestao-financeira-leva-90-das-pmes-a-crise/"
U_PRECO = "https://sebraepr.com.br/comunidade/artigo/precificacao-de-produtos-como-o-pequeno-empreendedor-define-o-preco-certo"
U_SERASA = "https://www.serasaexperian.com.br/sala-de-imprensa/indicadores/inadimplencia-chegou-a-9-milhoes-de-empresas-em-julho-e-dividas-somaram-238-bilhoes-revela-serasa-experian/"
U_INFLOW = "https://inflowinventory.com/blog/state-of-inventory-management-2026"
U_NEOGRID = "https://www.opovo.com.br/noticias/economia/2026/01/12/christiane-cruz-da-neogrid-supermercados-tem-rs-6-bilhoes-imobilizados-em-itens-de-baixo-giro.html"
U_ESTOQUE_SEBRAE = "https://sebrae.com.br/Sebrae/Portal%20Sebrae/UFs/RJ/Click%20Empreendedor/GEST%C3%83O%20DE%20ESTOQUES%20NO%20VAREJO.pdf"
U_CMV = "https://centraldovarejo.com.br/?p=45839"
U_BLOOMBERG = "https://www.bloomberglinea.com.br/negocios/contra-conta-de-padaria-foodtech-fatura-r-24-mi-com-corte-em-custo-de-restaurantes/"
U_CLINICA = "https://acontecendoaqui.com.br/empreendedorismo/alerta-falta-de-pacientes-pode-comprometer-ate-32-da-agenda-de-clinicas-no-pais/"
U_OBRAS = "https://bdtd.ibict.br/vufind/Record/UFSM_c7dffd5aa1e6218c3ca41195f7cea89c"
U_OFICINA = "https://actana.com.br/blog/ordem-de-servico-oficina-mecanica-guia-completo-para-organizar-e-profissionalizar-seu-negocio"
U_MEI = "https://sebraepr.com.br/comunidade/artigo/educacao-financeira-como-separar-financas-pessoais-e-empresariais"
U_MEI2 = "https://netcpa.com.br/colunas/como-separar-as-financas-pessoais-das-financas-da-empresa-sendo-mei/25542"
U_CRM = "https://www.agendor.com.br/blog/?p=41938"
U_ACADEMIA = "https://nfe.io/blog/?p=5390"
U_SALAO = "https://www.planilhadefluxo.com.br/para/saloes-de-beleza"
U_IMOB = "https://www.cora.com.br/blog/reduzir-inadimplencia-alugueis-imobiliarias/"
U_MKTPLACE = "https://blog.bling.com.br/?p=13535"
U_MKTPLACE2 = "https://contabilidade.com/blog/quanto-custa-vender-em-marketplace-veja-todas-as-taxas-e-custos/"
U_RH = "https://meucontadoronline.com.br/blog/passivo-trabalhista-erros-que-seu-negocio-nao-pode-cometer"
U_BANCOHORAS = "https://amdjus.com.br/?p=34045"
U_MKT = "https://www.tupi.fm/brasil/empresas-que-investem-em-marketing-melhoram-sua-lucratividade-em-30/"
U_POUSADA = "https://cursa.app/pt/pagina/pricing-promocoes-e-estrategias-para-aumentar-receita-nocoes-de-gestao-de-receita-ocupacao-diaria-media-e-mix-de-canais"
U_COMISSAO = "https://www.abcdacomunicacao.com.br/empresas-ainda-erram-no-calculo-de-comissoes-e-colocam-em-risco-produtividade-e-retencao-de-vendedores/"
U_COMISSAO2 = "https://www.portaltela.com/economia/2026/04/27/erros-de-gestao-elevam-turnover-nas-empresas/"
U_GIRO = "https://www.infomoney.com.br/?p=1437010"
U_ESCOLA = "https://www.cora.com.br/blog/ferramentas/guia-de-gestao-escolar/"
U_ESCOLA2 = "https://www.melhorescola.com.br/blog/?p=25402"
U_ACCT = "https://www.accountingtoday.com/news/small-businesses-challenged-by-cash-flow"

# (id, nome, segmento, pasta, status, subnotas, forca, problema, quem, evidencia, hoje, solucao,
#  beneficio, potencial, complexidade, concorrentes, diferencial)
OPS = [
 dict(id=1, nome="Fluxo de Caixa Inteligente", seg="Todas as empresas", pasta="financeiro/fluxo-de-caixa", status="Produzido",
      sub=(30,15,15,14,10,9,5), forca="Alta",
      problema="O dono não sabe quanto realmente sobra no fim do mês nem se o caixa vai aguentar os próximos meses.",
      quem="Micro e pequenas empresas, MEIs, autônomos, lojas, serviços.",
      evid=[("Fontes que citam o Sebrae apontam falta de controle financeiro/fluxo de caixa entre as principais causas de fechamento nos primeiros anos (percentuais variam por fonte: 48% a 50%; fonte primária não localizada)", U_FECHAMENTO),
            ("Instituto Locomotiva: 90% das PMEs enfrentam dificuldades financeiras e a ausência de gestão estruturada é a principal causa", U_LOCOMOTIVA),
            ("Levantamento citado pelo Accounting Today (EUA): 83% dos pequenos negócios apontam ter caixa operacional suficiente como problema nº 1", U_ACCT)],
      hoje="Caderno, extrato do banco, planilha improvisada ou 'de cabeça'.",
      solucao="Lançamentos de entradas/saídas (previsto x realizado), saldo acumulado mês a mês, projeção, alerta de saldo negativo e meses de reserva.",
      beneficio="Enxergar o saldo real e futuro; antecipar buracos de caixa; separar pró-labore do lucro.",
      potencial="Altíssimo: todo negócio precisa; compra recorrente por indicação.", complexidade="Média",
      concorrentes="Modelos gratuitos de blogs/Sebrae; apps (Conta Azul, Nibo, Granatum); planilhas pagas no Hotmart/Mercado Livre.",
      dif="Previsto x realizado, alerta por categoria, meses de reserva e dashboard; tutorial passo a passo e exemplo preenchido."),
 dict(id=2, nome="Precificador de Produtos e Serviços", seg="Comércio, serviços, indústria", pasta="precificacao/precificador", status="Produzido",
      sub=(29,14,15,14,10,9,5), forca="Alta",
      problema="Preço definido por intuição ou copiando a concorrência: vende muito e não sobra lucro; confunde markup com margem.",
      quem="Lojas, prestadores de serviço, confeiteiras, artesãos, e-commerce, MEIs.",
      evid=[("Sebrae PR: muitos empreendedores definem preço por intuição, cálculos superficiais ou só olhando a concorrência; precificação é uma das maiores dificuldades; markup e margem são confundidos", U_PRECO),
            ("Marketplaces: comissão + frete + taxa fixa + anúncios corroem a margem; margem deve ser calculada por canal e produto", U_MKTPLACE)],
      hoje="Preço do concorrente, 'custo x 2' ou calculadoras genéricas.",
      solucao="Preço = custo / (1 - soma dos % variáveis - lucro), com impostos, comissão, taxa de cartão/plataforma e rateio de despesa fixa; custo-hora para serviços; simulador de desconto.",
      beneficio="Preço que garante o lucro desejado; mostra o impacto real de dar desconto.",
      potencial="Altíssimo: dor universal e fácil de demonstrar valor.", complexidade="Média",
      concorrentes="Calculadoras online grátis; planilhas Sebrae; ERPs.",
      dif="Produtos + serviços + simulador de desconto ('quanto preciso vender a mais') + semáforo de margem."),
 dict(id=3, nome="Estoque Inteligente com Curva ABC", seg="Lojas, distribuidores, e-commerce", pasta="estoque/estoque-inteligente", status="Produzido",
      sub=(28,15,14,14,10,9,5), forca="Alta",
      problema="Falta do que vende e excesso do que não vende: caixa parado em estoque e vendas perdidas por ruptura.",
      quem="Lojas físicas, e-commerce, distribuidores, papelarias, farmácias, autopeças.",
      evid=[("Pesquisa 2026 de gestão de estoque: planilhas (Excel/Sheets) são usadas por 84,8% dos respondentes; software dedicado por 22%", U_INFLOW),
            ("Neogrid/O Povo: supermercados têm R$ 6 bi imobilizados em itens de baixo giro; 36 dias de estoque vs benchmark de 23", U_NEOGRID),
            ("Sebrae: excesso de estoque prende o caixa do lojista; curva ABC é a ferramenta recomendada", U_ESTOQUE_SEBRAE)],
      hoje="Contagem manual, planilha sem alerta, ou ERP caro subutilizado.",
      solucao="Cadastro + movimentações, estoque atual, mínimo, status (ruptura/repor/ok/excesso), sugestão de compra, itens parados e curva ABC automática com gráfico de Pareto.",
      beneficio="Libera capital parado e evita ruptura dos itens que mais vendem.",
      potencial="Muito alto.", complexidade="Alta",
      concorrentes="Planilhas gratuitas de estoque; Bling/Tiny (ERPs).",
      dif="ABC automático sem macros, alertas de reposição e itens parados com valor imobilizado."),
 dict(id=4, nome="Contas a Pagar e Receber com Inadimplência", seg="Todas as empresas", pasta="financeiro/contas-pagar-receber", status="Produzido",
      sub=(28,15,14,14,10,8,5), forca="Alta",
      problema="Contas vencem sem ninguém ver, clientes atrasam sem cobrança organizada e a inadimplência corrói o caixa.",
      quem="Prestadores de serviço, escolas, academias, distribuidores, qualquer empresa com venda a prazo.",
      evid=[("Serasa Experian (jul/2026): recorde de 9,2 milhões de CNPJs negativados, dívidas de R$ 238,6 bi; 8,7 milhões são micro e pequenas empresas", U_SERASA),
            ("Fontes citando o Sebrae: 50% das micro e pequenas empresas fecham por inadimplência, falta de capital e falta de lucro (dado secundário)", U_FECHAMENTO)],
      hoje="Boletos em papel, agenda, WhatsApp e memória.",
      solucao="Registro de títulos a pagar/receber, status automático, aging por faixa de atraso, juros e multa, ranking de devedores, mensagem de cobrança pronta e previsão de 8 semanas.",
      beneficio="Nunca mais pagar multa por esquecimento; cobrar na hora certa; prever saldo semanal.",
      potencial="Muito alto.", complexidade="Alta",
      concorrentes="Apps de cobrança; planilhas simples de contas a pagar.",
      dif="Aging + ranking de devedores + mensagem de cobrança pronta + previsão semanal."),
 dict(id=5, nome="CRM e Funil de Vendas com Follow-up", seg="Serviços, B2B, imobiliárias, vendas consultivas", pasta="vendas/crm-funil", status="Produzido",
      sub=(25,14,14,14,10,10,5), forca="Média",
      problema="Leads esfriam por falta de follow-up; oportunidades 'somem' entre WhatsApp, e-mail e papel.",
      quem="Equipes comerciais pequenas, prestadores de serviço, corretores, consultores.",
      evid=[("Agendor: não agendar o próximo passo deixa a oportunidade estagnada no funil e o lead esfria ou é abordado por concorrentes (conteúdo de fornecedor de CRM)", U_CRM)],
      hoje="WhatsApp + memória; CRMs pagos subutilizados.",
      solucao="Leads por etapa com probabilidade, valor ponderado, alerta de follow-up atrasado, agenda do dia, ranking de vendedores, conversão por origem e metas.",
      beneficio="Menos oportunidades perdidas; previsão de vendas; saber qual canal converte.",
      potencial="Alto.", complexidade="Alta",
      concorrentes="CRMs gratuitos (HubSpot, RD CRM), modelos Excel de blogs.",
      dif="Funciona offline, sem mensalidade, com agenda de follow-up automática."),
 dict(id=6, nome="DRE e Ponto de Equilíbrio", seg="Empresas com contador/sem visão de lucro", pasta="financeiro/dre-ponto-equilibrio", status="Produzido",
      sub=(27,12,14,14,9,10,5), forca="Média",
      problema="Fatura bem mas não sabe se tem lucro; não sabe quanto precisa vender para pagar as contas.",
      quem="Pequenas e médias empresas, sócios, gestores financeiros iniciantes.",
      evid=[("Instituto Locomotiva: ausência de gestão estruturada como principal causa das dificuldades financeiras (90% das PMEs)", U_LOCOMOTIVA),
            ("Sebrae (via fontes secundárias): lucro e capital insuficientes figuram entre as causas de fechamento", U_FECHAMENTO)],
      hoje="Demonstrativo do contador meses depois; ou nenhum.",
      solucao="Lançamentos classificados por conta do DRE; DRE mensal com análise vertical, margem de contribuição, ponto de equilíbrio e margem de segurança.",
      beneficio="Saber o lucro real por mês e a meta mínima de faturamento.",
      potencial="Alto.", complexidade="Média",
      concorrentes="Modelos de DRE de blogs contábeis.",
      dif="DRE + ponto de equilíbrio integrados e alimentados por um único lançamento."),
 dict(id=7, nome="Ficha Técnica e CMV para Restaurantes", seg="Restaurantes, lanchonetes, padarias, delivery", pasta="restaurantes/ficha-tecnica-cmv", status="Produzido",
      sub=(27,13,11,14,10,10,5), forca="Alta",
      problema="Cardápio precificado 'no feeling'; CMV alto por desperdício, porção irregular e fornecedor caro, sem saber onde.",
      quem="Restaurantes, bares, lanchonetes, pizzarias, hamburguerias, confeitarias.",
      evid=[("Cartilha Abrasel citada pelo Central do Varejo: CMV de referência entre 25% e 40%; CMV muito alto aponta desperdício, furto ou fornecedor fora do mercado", U_CMV),
            ("Estudo de caso (UnB, 2008): CMV caiu de 24,8% para 15,6% após fichas técnicas de preparo (caso único, antigo)", "https://bdm.unb.br/bitstream/10483/348/1/2008_FabianaMariaSouza.pdf"),
            ("Bloomberg Línea: diferença entre CMV teórico (ficha técnica) e CMV real revela perdas", U_BLOOMBERG)],
      hoje="Preço copiado do vizinho; cálculo de CMV só no fim do mês, quando existe.",
      solucao="Insumos com fator de correção, fichas técnicas com custo por porção, CMV por prato, preço sugerido pela meta, engenharia de cardápio, CMV real x teórico mensal e registro de desperdício.",
      beneficio="Descobrir pratos que dão prejuízo e reduzir perdas.",
      potencial="Alto (nicho com muita dor e disposição a pagar).", complexidade="Alta",
      concorrentes="Planilhas Stone/Foodness gratuitas; softwares (Saipos).",
      dif="Engenharia de cardápio + CMV real x teórico + desperdício na mesma planilha."),
 dict(id=8, nome="Ordem de Serviço para Oficinas", seg="Oficinas mecânicas, funilarias, auto elétrica", pasta="oficinas/ordem-de-servico", status="Produzido",
      sub=(25,14,11,14,9,10,5), forca="Média",
      problema="Orçamento no WhatsApp, peça 'de cabeça', estoque que some, caixa que não fecha com o movimento real.",
      quem="Oficinas mecânicas, auto centers, retíficas, funilarias.",
      evid=[("Material de fornecedor (Actana): peças sem vínculo com a OS fazem o estoque 'sumir'; orçamentos informais; falta de visão financeira (evidência de fornecedor, sem estudo independente)", U_OFICINA)],
      hoje="Talão de OS em papel, WhatsApp e caderno.",
      solucao="Clientes, veículos, peças, OS com itens, mão de obra, lucro por OS, contas a receber, histórico por placa e painel mensal.",
      beneficio="Controle de peças por OS, lucro por serviço e dinheiro a receber.",
      potencial="Alto.", complexidade="Alta",
      concorrentes="Sistemas pagos para oficina.",
      dif="Lucro por OS e histórico por placa em planilha, sem mensalidade."),
 dict(id=9, nome="Controle de Obras (Orçado x Realizado)", seg="Construtoras pequenas, reformas, engenheiros autônomos", pasta="construcao/controle-de-obras", status="Produzido",
      sub=(26,11,11,15,9,10,5), forca="Média",
      problema="Obra estoura custo e prazo; o dono só descobre a margem no fim.",
      quem="Pequenas construtoras, empreiteiros, engenheiros e arquitetos, reformas.",
      evid=[("Pesquisa com construtoras brasileiras (UFSM): média de 6,52% de estouro de orçamento e 21,26% de estouro de cronograma (100 respostas); causas centradas em orçamento, planejamento e suprimentos", U_OBRAS)],
      hoje="Caderno do mestre de obras, notas fiscais soltas.",
      solucao="Orçamento por etapa, custos lançados por etapa/categoria, cronograma com Gantt, % físico, projeção de custo final (EAC), medições e margem prevista.",
      beneficio="Detecta estouro durante a obra e projeta a margem final.",
      potencial="Alto (ticket mais alto).", complexidade="Alta",
      concorrentes="Softwares como Sienge/Obra Prima (caros); planilhas de engenharia.",
      dif="Projeção de margem + Gantt automático + medições em um arquivo."),
 dict(id=10, nome="Agenda, Faltas e Retornos para Clínicas", seg="Clínicas, consultórios, odonto, estética", pasta="clinicas/agenda-retornos", status="Produzido",
      sub=(26,13,10,13,9,10,5), forca="Média",
      problema="Pacientes faltam e a agenda fica vazia; retornos não são reagendados; receita perdida sem medição.",
      quem="Consultórios e clínicas (odonto, fisioterapia, psicologia, estética).",
      evid=[("Conclínica: no-show pode comprometer até 32% da agenda em algumas clínicas (dado de fornecedor)", U_CLINICA),
            ("Estudo acadêmico citado: taxa média de no-show de 18,8% em centro médico dos EUA (1997-2008)", U_CLINICA)],
      hoje="Agenda de papel/Google Agenda sem indicador de faltas.",
      solucao="Agenda com status, confirmações pendentes, taxa de falta por profissional e dia da semana, receita perdida, fila de retornos e recebimentos. Sem dados clínicos.",
      beneficio="Reduz faltas (confirmação) e recupera retornos.",
      potencial="Alto.", complexidade="Média",
      concorrentes="Softwares de clínica (Amplimed, Clinic Plus).",
      dif="Mede a receita perdida por faltas e sugere confirmações; sem dados sensíveis."),
 # ---------------- roadmap ----------------
 dict(id=11, nome="Comissão e Metas de Vendedores", seg="Equipes de vendas", pasta="vendas/comissao-metas", status="Roadmap",
      sub=(22,12,12,14,10,10,5), forca="Média",
      problema="Cálculo manual de comissão gera erro, desconfiança da equipe e rotatividade.",
      quem="Lojas, imobiliárias, concessionárias, equipes comerciais.",
      evid=[("Especialistas: processos manuais e regras pouco claras estão entre os erros mais comuns no cálculo de comissões", U_COMISSAO),
            ("Portal Tela: erros de cálculo abalam a confiança e se ligam a maior turnover", U_COMISSAO2)],
      hoje="Planilha avulsa, cálculo na calculadora.", solucao="Regras por faixa, extrato individual, ranking e metas.",
      beneficio="Pagamento correto e transparente.", potencial="Alto (kit vendas).", complexidade="Média",
      concorrentes="Modelos gratuitos de blogs.", dif="Extrato por vendedor e faixas configuráveis."),
 dict(id=12, nome="Separação PF/PJ e Pró-labore (MEI)", seg="MEIs e autônomos", pasta="financeiro/pf-pj-pro-labore", status="Roadmap",
      sub=(25,12,13,12,10,8,5), forca="Alta",
      problema="O dono mistura dinheiro da empresa com o pessoal e sente que o negócio 'nunca prospera'.",
      quem="MEIs, autônomos, microempresas familiares.",
      evid=[("Pesquisa Sebrae citada: 45% dos MEIs não separam contas pessoais das da empresa; 60% dos donos de pequenos negócios já usaram recursos pessoais na empresa", U_MEI),
            ("Mistura de contas causa 'confusão patrimonial' e dificulta calcular o lucro", U_MEI2)],
      hoje="Uma conta só, sem registro.", solucao="Pró-labore fixo, retiradas, aportes, lucro disponível.",
      beneficio="Clareza do lucro e disciplina de retirada.", potencial="Alto em volume; ticket baixo.", complexidade="Baixa",
      concorrentes="App gratuito do Sebrae para MEI.", dif="Pró-labore e reserva integrados (já parcialmente no Fluxo de Caixa)."),
 dict(id=13, nome="Precificador Marketplace (premium do Precificador)", seg="E-commerce e marketplaces", pasta="precificacao/precificador-marketplace", status="Roadmap",
      sub=(24,13,11,13,9,9,5), forca="Média",
      problema="Comissão, frete, taxa fixa e anúncios eliminam a margem sem o vendedor perceber.",
      quem="Vendedores de Mercado Livre, Shopee, Amazon, Magalu.",
      evid=[("Bling: taxas de marketplace precisam ser controladas por canal", U_MKTPLACE),
            ("Contabilidade.com: comissões de 10% a 20% + taxas fixas + frete", U_MKTPLACE2)],
      hoje="Calculadoras de cada marketplace.", solucao="Preço mínimo por canal com tabela de taxas editável.",
      beneficio="Margem real por canal.", potencial="Alto.", complexidade="Média",
      concorrentes="ERPs e extensões de navegador.", dif="Comparar canais lado a lado."),
 dict(id=14, nome="Capital de Giro (PMR, PMP e necessidade)", seg="Comércio e serviços com venda a prazo", pasta="financeiro/capital-de-giro", status="Roadmap",
      sub=(24,10,13,14,9,10,4), forca="Média",
      problema="Vende a prazo, paga à vista e não sabe quanto capital de giro precisa.",
      quem="Distribuidores, atacadistas, indústrias pequenas.",
      evid=[("InfoMoney: fórmula do Sebrae (contas a receber + estoque - contas a pagar) e prazos médios", U_GIRO),
            ("Pesquisas antigas citam falta de capital de giro como 1ª causa de fechamento (Sebrae 2004, via terceiros)", U_GIRO)],
      hoje="Descobre quando falta dinheiro.", solucao="PMR, PMP, ciclo financeiro e necessidade de giro.",
      beneficio="Evita empréstimo caro.", potencial="Médio-alto.", complexidade="Média",
      concorrentes="Calculadoras simples.", dif="Alimentado pelos dados do Contas a Pagar/Receber."),
 dict(id=15, nome="Orçamento Empresarial (Planejado x Realizado)", seg="PMEs", pasta="financeiro/orcamento-empresarial", status="Roadmap",
      sub=(21,10,13,14,9,10,5), forca="Fraca",
      problema="Empresas operam sem orçamento ou meta de gasto por categoria.",
      quem="PMEs com mais de um centro de custo.",
      evid=[("Levantamento citado (EUA): 51% dos pequenos negócios não usam orçamento ou previsão", U_ACCT)],
      hoje="Nenhum.", solucao="Orçamento anual por categoria com desvio mensal.",
      beneficio="Disciplina de gastos.", potencial="Médio.", complexidade="Média",
      concorrentes="Modelos gratuitos.", dif="Integra com Fluxo de Caixa."),
 dict(id=16, nome="Aluguéis e Contratos (Imobiliárias)", seg="Imobiliárias e administradores de imóveis", pasta="imobiliarias/alugueis-contratos", status="Roadmap",
      sub=(24,13,9,13,9,10,5), forca="Média",
      problema="Inadimplência de aluguel, reajustes esquecidos e contratos que vencem sem aviso.",
      quem="Imobiliárias pequenas e proprietários com vários imóveis.",
      evid=[("Cora: inadimplência desgasta o fluxo de caixa; recomenda cobrança preventiva e regras claras; reajuste por IGP-M/IPCA anual", U_IMOB)],
      hoje="Pastas de contrato e agenda.", solucao="Cadastro, vencimentos, reajuste, atraso com multa/juros e alertas de fim de contrato.",
      beneficio="Receita previsível e reajuste no prazo.", potencial="Médio-alto.", complexidade="Média",
      concorrentes="Sistemas de locação.", dif="Alertas de reajuste e fim de contrato."),
 dict(id=17, nome="RH: Férias, Banco de Horas e Horas Extras", seg="PMEs com equipe CLT", pasta="rh/ferias-banco-horas", status="Roadmap",
      sub=(23,12,12,12,8,10,5), forca="Média",
      problema="Férias vencidas (pagas em dobro), horas extras mal calculadas e banco de horas sem controle geram passivo trabalhista.",
      quem="Empresas com 5 a 50 funcionários.",
      evid=[("Contador Online: principal causa de passivo é hora extra não paga ou mal registrada", U_RH),
            ("AmdJus: banco de horas sem acordo válido pode virar pagamento de horas extras", U_BANCOHORAS)],
      hoje="Controle verbal; contador pontual.", solucao="Calendário de férias, saldo de horas e alertas de vencimento.",
      beneficio="Evita multas e passivos.", potencial="Médio-alto.", complexidade="Média-alta (regras da CLT; validar com contador)",
      concorrentes="Sistemas de ponto.", dif="Alertas de vencimento de férias."),
 dict(id=18, nome="Salão e Barbearia: Comissões e Caixa", seg="Salões, barbearias, estéticas", pasta="saloes/comissoes-caixa", status="Roadmap",
      sub=(24,13,9,11,9,10,5), forca="Média",
      problema="Cada profissional tem um % diferente; sem controle não se sabe quais serviços dão lucro após a comissão.",
      quem="Salões e barbearias com 2 a 15 profissionais.",
      evid=[("Material de gestão para salões: comissão por profissional, caixa irregular, produtos de revenda misturados aos de uso interno", U_SALAO)],
      hoje="Caderno e fechamento manual.", solucao="Atendimentos, comissão automática, caixa diário, custo por serviço.",
      beneficio="Comissão sem briga e lucro por serviço.", potencial="Alto em volume.", complexidade="Média",
      concorrentes="Apps de agenda (Trinks, Belasis).", dif="Sem mensalidade."),
 dict(id=19, nome="Escola: Mensalidades e Inadimplência", seg="Escolas e cursos livres", pasta="escolas/mensalidades", status="Roadmap",
      sub=(25,12,8,12,9,9,5), forca="Média",
      problema="Mais de 61% dos gestores escolares citam inadimplência e falta de capital como principais problemas financeiros.",
      quem="Escolas pequenas, creches, cursos livres, reforço escolar.",
      evid=[("Pesquisa Educbank citada pelo Melhor Escola: 61% dos gestores (fonte de fornecedor)", U_ESCOLA2),
            ("Cora: cobrança sem automação consome tempo e reduz previsibilidade", U_ESCOLA)],
      hoje="Boletos e planilhas soltas.", solucao="Alunos, mensalidades, atrasos, acordos e fluxo.",
      beneficio="Previsibilidade de receita.", potencial="Médio.", complexidade="Média",
      concorrentes="Sistemas escolares.", dif="Preço único."),
 dict(id=20, nome="Marketing: CAC, ROI e Campanhas", seg="Pequenos negócios que anunciam", pasta="marketing/cac-roi", status="Roadmap",
      sub=(20,11,13,12,9,9,5), forca="Fraca",
      problema="Anuncia sem saber quanto custa trazer um cliente nem o retorno.",
      quem="Lojas, clínicas e prestadores que usam Meta/Google Ads.",
      evid=[("Estudo LLYC/ROI Marketing Institute (via Tupi): empresas que medem ROI têm lucratividade ~31% maior; apenas 12% usam ROI (amostra sem recorte por porte)", U_MKT)],
      hoje="Olha 'cliques'.", solucao="Investimento, leads, vendas, CAC, ROI e conversão por canal.",
      beneficio="Corta canais que não dão retorno.", potencial="Médio.", complexidade="Baixa-média",
      concorrentes="Dashboards gratuitos.", dif="Simples para donos."),
 dict(id=21, nome="Pacote de Indicadores (KPI Pack)", seg="PMEs em geral", pasta="gestao/kpi-pack", status="Roadmap",
      sub=(20,11,14,12,8,9,5), forca="Fraca",
      problema="Gestão por intuição, sem painel único de indicadores.",
      quem="Gestores de PMEs.",
      evid=[("Instituto Locomotiva: ausência de gestão estruturada", U_LOCOMOTIVA)],
      hoje="Nenhum painel.", solucao="Painel com indicadores-chave da empresa.", beneficio="Visão geral.",
      potencial="Médio.", complexidade="Média", concorrentes="BI gratuitos.", dif="Pronto para uso."),
 dict(id=22, nome="Pousada: Ocupação, Diária Média e RevPAR", seg="Pousadas e hotéis pequenos", pasta="hospedagem/ocupacao-revpar", status="Roadmap",
      sub=(24,12,8,12,8,10,5), forca="Média",
      problema="Ocupação alta com desconto excessivo mascara receita ruim; sem ADR e RevPAR não há decisão de preço.",
      quem="Pousadas, hostels e hotéis de até 40 quartos.",
      evid=[("Material de gestão de receita: TO, ADR e RevPAR como indicadores centrais e exemplo de pousada de 20 quartos", U_POUSADA)],
      hoje="Livro de reservas.", solucao="Reservas, ocupação diária, ADR, RevPAR e mix de canais.",
      beneficio="Preço dinâmico por temporada.", potencial="Médio.", complexidade="Média",
      concorrentes="PMS e channel managers.", dif="Entrada manual simples."),
 dict(id=23, nome="Academia: Alunos, Mensalidades e Evasão", seg="Academias e estúdios", pasta="academias/alunos-evasao", status="Roadmap",
      sub=(23,12,9,11,9,9,5), forca="Fraca",
      problema="Rotatividade alta e inadimplência impedem o crescimento da receita.",
      quem="Academias de bairro, estúdios de pilates e lutas.",
      evid=[("NFE.io: donos são ótimos profissionais mas sem preparo em gestão; planos longos reduzem inadimplência e evasão (conteúdo de fornecedor)", U_ACADEMIA)],
      hoje="Sistema de catraca + caderno.", solucao="Matrículas, planos, vencimentos, inadimplência e churn.",
      beneficio="Retenção.", potencial="Médio.", complexidade="Média",
      concorrentes="Softwares de academia.", dif="Preço único."),
 dict(id=24, nome="Compras e Comparador de Fornecedores", seg="Comércio e restaurantes", pasta="estoque/comparador-fornecedores", status="Roadmap",
      sub=(18,11,12,12,9,10,5), forca="Fraca",
      problema="Compra sem cotação: paga mais do que o necessário.",
      quem="Lojas, restaurantes e oficinas.",
      evid=[("CMV alto apontado como sintoma de fornecedor fora do preço de mercado (Abrasel via Central do Varejo)", U_CMV)],
      hoje="Liga para dois fornecedores.", solucao="Cotações lado a lado com melhor preço e prazo.",
      beneficio="Economia nas compras.", potencial="Médio.", complexidade="Baixa",
      concorrentes="Planilhas simples.", dif="Histórico de preços."),
 dict(id=25, nome="Controle de Empréstimos e Dívidas", seg="PMEs endividadas", pasta="financeiro/emprestimos-dividas", status="Roadmap",
      sub=(22,8,12,11,9,10,4), forca="Média",
      problema="Cada empresa inadimplente acumula em média 7,3 contas em atraso e dívida média de R$ 26 mil.",
      quem="Pequenas empresas com várias dívidas.",
      evid=[("Serasa Experian (jul/2026): 7,3 contas negativadas e dívida média de R$ 25.983,88 por CNPJ", U_SERASA)],
      hoje="Lista mental.", solucao="Cadastro de dívidas, parcelas, juros e plano de quitação (bola de neve).",
      beneficio="Plano de saída do endividamento.", potencial="Médio.", complexidade="Média",
      concorrentes="Calculadoras.", dif="Plano de quitação."),
 dict(id=26, nome="Projeção Financeira e Cenários", seg="PMEs", pasta="financeiro/projecao-cenarios", status="Roadmap",
      sub=(18,9,12,13,8,10,5), forca="Fraca",
      problema="Não simula 'e se vender 20% menos?'.", quem="Gestores e sócios.",
      evid=[("Levantamento citado (EUA): maioria dos pequenos negócios sem orçamento ou previsão", U_ACCT)],
      hoje="Não simula.", solucao="Cenários otimista/base/pessimista.", beneficio="Decisão com risco medido.",
      potencial="Médio.", complexidade="Média", concorrentes="Modelos de blogs.", dif="Integra com DRE."),
 dict(id=27, nome="Validade e Lotes", seg="Alimentos, farmácias, cosméticos", pasta="estoque/validade-lotes", status="Roadmap",
      sub=(20,11,9,12,8,9,5), forca="Fraca",
      problema="Produtos vencem na prateleira.", quem="Mercadinhos, farmácias, padarias.",
      evid=[("Abrasel (via trabalho acadêmico): restaurantes descartam em média 5 kg de alimentos por dia", "https://www.arandu.ufrpe.br/bitstreams/4b024a07-e53d-4523-b36b-b837f96a769c/download")],
      hoje="Olho e etiqueta.", solucao="Lotes com alerta de vencimento.", beneficio="Menos perdas.",
      potencial="Médio.", complexidade="Média", concorrentes="ERPs.", dif="Alerta 30/60/90 dias."),
 dict(id=28, nome="Delivery: Margem por Plataforma", seg="Restaurantes com delivery", pasta="restaurantes/delivery-margem", status="Roadmap",
      sub=(16,12,9,12,8,10,5), forca="Fraca",
      problema="Taxas de aplicativos reduzem a margem do prato.", quem="Restaurantes.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Mesmo preço em todos os canais.", solucao="Preço e margem por plataforma.", beneficio="Margem protegida.",
      potencial="Médio.", complexidade="Baixa", concorrentes="Calculadoras.", dif="Usa a ficha técnica."),
 dict(id=29, nome="Controle de Desperdício", seg="Restaurantes e padarias", pasta="restaurantes/desperdicio", status="Roadmap",
      sub=(20,10,8,10,8,9,5), forca="Média",
      problema="Sobras e perdas não são medidas.", quem="Restaurantes e cozinhas industriais.",
      evid=[("Abrasel (via UFRPE): 5 kg/dia descartados por restaurante; sobras de 9,55% em fast food e 11,3% em serviço completo", "https://www.arandu.ufrpe.br/bitstreams/4b024a07-e53d-4523-b36b-b837f96a769c/download")],
      hoje="Não mede.", solucao="Registro por motivo (já incluso na Ficha Técnica e CMV).", beneficio="Redução de perdas.",
      potencial="Médio.", complexidade="Baixa", concorrentes="Apps de redução de desperdício.", dif="Integrado ao CMV."),
 dict(id=30, nome="Escala de Equipe e Turnos", seg="Lojas, restaurantes, clínicas", pasta="rh/escala-turnos", status="Roadmap",
      sub=(14,11,10,10,8,10,5), forca="Fraca",
      problema="Escala feita na mão gera conflito.", quem="Gestores de equipes.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Papel no mural.", solucao="Escala mensal com validação.", beneficio="Menos conflito.",
      potencial="Baixo-médio.", complexidade="Média", concorrentes="Apps gratuitos.", dif="Baixo."),
 dict(id=31, nome="Manutenção Preventiva de Equipamentos", seg="Indústrias pequenas, oficinas, clínicas", pasta="manutencao/preventiva", status="Roadmap",
      sub=(14,10,8,12,8,9,5), forca="Fraca",
      problema="Equipamento quebra por falta de manutenção planejada.", quem="Indústrias e prestadores.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Reativa.", solucao="Plano e alertas.", beneficio="Menos paradas.",
      potencial="Baixo-médio.", complexidade="Média", concorrentes="CMMS.", dif="Baixo."),
 dict(id=32, nome="Controle de Projetos e Tarefas", seg="Agências, escritórios", pasta="gestao/projetos-tarefas", status="Roadmap",
      sub=(12,10,12,9,8,8,5), forca="Fraca",
      problema="Prazos perdidos.", quem="Equipes pequenas.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Trello, WhatsApp.", solucao="Quadro e prazos.", beneficio="Prazo cumprido.",
      potencial="Baixo.", complexidade="Média", concorrentes="Trello, Notion (gratuitos).", dif="Baixo."),
 dict(id=33, nome="Onboarding e Treinamentos", seg="PMEs com equipe", pasta="rh/onboarding-treinamentos", status="Roadmap",
      sub=(13,7,10,9,8,10,5), forca="Fraca",
      problema="Novos funcionários demoram a render.", quem="Gestores.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Informal.", solucao="Checklist e trilha.", beneficio="Integração rápida.",
      potencial="Baixo.", complexidade="Baixa", concorrentes="Modelos gratuitos.", dif="Baixo."),
 dict(id=34, nome="Calendário de Conteúdo", seg="Marketing", pasta="marketing/calendario-conteudo", status="Roadmap",
      sub=(10,10,12,7,9,8,4), forca="Fraca",
      problema="Postagens irregulares.", quem="Social media.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Notion e papel.", solucao="Calendário editorial.", beneficio="Consistência.",
      potencial="Baixo.", complexidade="Baixa", concorrentes="Gratuitos abundantes.", dif="Baixo."),
 dict(id=35, nome="Metas e OKR", seg="Gestão", pasta="gestao/metas-okr", status="Roadmap",
      sub=(10,7,10,9,8,9,5), forca="Fraca",
      problema="Equipe sem meta clara.", quem="Gestores.",
      evid=[("Sem fonte quantitativa localizada nesta rodada: validar", "")],
      hoje="Reuniões.", solucao="Metas e acompanhamento.", beneficio="Foco.",
      potencial="Baixo.", complexidade="Baixa", concorrentes="Gratuitos.", dif="Baixo."),
]

for o in OPS:
    o["nota"] = sum(o["sub"])
